const Damages = {
    LIGHTNING: LightningDamage,
    FALL: FallDamage,
    FALLING_BLOCK: FallingBlockDamage,
    THORNS: ThornsDamage,
    SUFFOCATION: SuffocationDamage, CRAMMING: EntityCrammingDamage,
    DROWNING: DrowningDamage,
    STARVATION: StarvationDamage,
    CACTUS: CactusDamage,
    BERRY_BUSH: BerryBushDamage,
    FIRE: FireDamage,
    LAVA: LavaDamage,
    BURNING: BurningDamage,
    MAGMA: MagmaDamage,
    CAMPFIRE: CampfireDamage,
    POTION: PotionDamage, INSTANT_DAMAGE: InstantDamage, POISON: PoisonDamage, WITHER: WitherDamage,
    VOID: VoidDamage,
    EXPLOSION: ExplosionDamage, TNT: TNTDamage, FIREWORK: FireworkDamage,
    FREEZING: FreezingDamage,
    ATTACK: AttackDamage,
    MELEE: MeleeDamage
};

const DamageIds = {
    LIGHTNING: 0,
    FALL: 1,
    FALLING_BLOCK: 2,
    THORNS: 3,
    SUFFOCATION: 4, CRAMMING: 5,
    DROWNING: 6,
    STARVATION: 7,
    CACTUS: 8,
    BERRY_BUSH: 9,
    FIRE: 10,
    LAVA: 11,
    BURNING: 12,
    MAGMA: 13,
    CAMPFIRE: 14,
    POTION: 15, INSTANT_DAMAGE: 16, POISON: 17, WITHER: 18,
    VOID: 19,
    EXPLOSION: 20, TNT: 21, FIREWORK: 22,
    FREEZING: 23,
    ATTACK: 24,
    MELEE: 25,
    INTENTIONAL_GAME_DESIGN: 26
};