// ###################### //
//   AUTO GENERATED FILE
// ###################### //
const TextureList = [
 "blocks/air.png",
 "blocks/allium.png",
 "blocks/bedrock.png",
 "blocks/blue_orchid.png",
 "blocks/coal_ore.png",
 "blocks/cobblestone.png",
 "blocks/dandelion.png",
 "blocks/destroy_stage_0.png",
 "blocks/destroy_stage_1.png",
 "blocks/destroy_stage_2.png",
 "blocks/destroy_stage_3.png",
 "blocks/destroy_stage_4.png",
 "blocks/destroy_stage_5.png",
 "blocks/destroy_stage_6.png",
 "blocks/destroy_stage_7.png",
 "blocks/destroy_stage_8.png",
 "blocks/destroy_stage_9.png",
 "blocks/diamond_ore.png",
 "blocks/dirt.png",
 "blocks/fire.png",
 "blocks/fire_layer.png",
 "blocks/gold_ore.png",
 "blocks/grass.png",
 "blocks/grass_block.png",
 "blocks/grass_double.png",
 "blocks/gravel.png",
 "blocks/houstonia.png",
 "blocks/ice.png",
 "blocks/iron_ore.png",
 "blocks/lava_flow.png",
 "blocks/lava_still.png",
 "blocks/leaves_oak.png",
 "blocks/log_acacia.png",
 "blocks/log_big_oak.png",
 "blocks/log_birch.png",
 "blocks/log_jungle.png",
 "blocks/log_oak.png",
 "blocks/log_spruce.png",
 "blocks/orange_tulip.png",
 "blocks/oxeye_daisy.png",
 "blocks/packed_ice.png",
 "blocks/paeonia.png",
 "blocks/pink_tulip.png",
 "blocks/planks_acacia.png",
 "blocks/planks_big_oak.png",
 "blocks/planks_birch.png",
 "blocks/planks_jungle.png",
 "blocks/planks_oak.png",
 "blocks/planks_spruce.png",
 "blocks/red_tulip.png",
 "blocks/rose.png",
 "blocks/sand.png",
 "blocks/snowy_grass_block.png",
 "blocks/sponge.png",
 "blocks/stone.png",
 "blocks/tnt.png",
 "blocks/water_1.png",
 "blocks/water_2.png",
 "blocks/water_3.png",
 "blocks/water_4.png",
 "blocks/water_5.png",
 "blocks/water_6.png",
 "blocks/water_7.png",
 "blocks/water_8.png",
 "blocks/water_flow.png",
 "blocks/water_still.png",
 "blocks/wet_sponge.png",
 "blocks/white_tulip.png",
 "entities/cow.png",
 "entities/steve.png",
 "gui/bubble.png",
 "gui/bubble_pop.png",
 "gui/button.png",
 "gui/button_disabled.png",
 "gui/button_hover.png",
 "gui/crafting_table.png",
 "gui/cursor.png",
 "gui/empty_food.png",
 "gui/empty_heart.png",
 "gui/empty_heart_blink.png",
 "gui/food.png",
 "gui/half_food.png",
 "gui/half_heart.png",
 "gui/half_heart_blink.png",
 "gui/heart.png",
 "gui/heart_blink.png",
 "gui/hotbar.png",
 "gui/player_inventory.png",
 "gui/selected_hotbar.png",
 "items/apple.png",
 "items/coal.png",
 "items/cooked_beef.png",
 "items/diamond.png",
 "items/flint.png",
 "items/flint_and_steel.png",
 "items/gold_ingot.png",
 "items/iron_ingot.png",
 "items/leather.png",
 "items/raw_beef.png",
 "items/wheat_seeds.png",
 "particles/critical_hit.png",
 "particles/explosion_0.png",
 "particles/explosion_1.png",
 "particles/explosion_10.png",
 "particles/explosion_11.png",
 "particles/explosion_12.png",
 "particles/explosion_13.png",
 "particles/explosion_14.png",
 "particles/explosion_15.png",
 "particles/explosion_2.png",
 "particles/explosion_3.png",
 "particles/explosion_4.png",
 "particles/explosion_5.png",
 "particles/explosion_6.png",
 "particles/explosion_7.png",
 "particles/explosion_8.png",
 "particles/explosion_9.png",
 "sounds/damage/fallbig.ogg",
 "sounds/damage/fallsmall.ogg",
 "sounds/damage/hit1.ogg",
 "sounds/damage/hit2.ogg",
 "sounds/damage/hit3.ogg",
 "sounds/dig/cloth1.ogg",
 "sounds/dig/cloth2.ogg",
 "sounds/dig/cloth3.ogg",
 "sounds/dig/cloth4.ogg",
 "sounds/dig/coral1.ogg",
 "sounds/dig/coral2.ogg",
 "sounds/dig/coral3.ogg",
 "sounds/dig/coral4.ogg",
 "sounds/dig/glass1.ogg",
 "sounds/dig/glass2.ogg",
 "sounds/dig/glass3.ogg",
 "sounds/dig/grass1.ogg",
 "sounds/dig/grass2.ogg",
 "sounds/dig/grass3.ogg",
 "sounds/dig/grass4.ogg",
 "sounds/dig/gravel1.ogg",
 "sounds/dig/gravel2.ogg",
 "sounds/dig/gravel3.ogg",
 "sounds/dig/gravel4.ogg",
 "sounds/dig/sand1.ogg",
 "sounds/dig/sand2.ogg",
 "sounds/dig/sand3.ogg",
 "sounds/dig/sand4.ogg",
 "sounds/dig/snow1.ogg",
 "sounds/dig/snow2.ogg",
 "sounds/dig/snow3.ogg",
 "sounds/dig/snow4.ogg",
 "sounds/dig/stone1.ogg",
 "sounds/dig/stone2.ogg",
 "sounds/dig/stone3.ogg",
 "sounds/dig/stone4.ogg",
 "sounds/dig/wet_grass1.ogg",
 "sounds/dig/wet_grass2.ogg",
 "sounds/dig/wet_grass3.ogg",
 "sounds/dig/wet_grass4.ogg",
 "sounds/dig/wood1.ogg",
 "sounds/dig/wood2.ogg",
 "sounds/dig/wood3.ogg",
 "sounds/dig/wood4.ogg",
 "sounds/liquid/enter1.ogg",
 "sounds/liquid/enter2.ogg",
 "sounds/liquid/enter3.ogg",
 "sounds/liquid/exit1.ogg",
 "sounds/liquid/exit2.ogg",
 "sounds/liquid/exit3.ogg",
 "sounds/liquid/heavy_splash.ogg",
 "sounds/liquid/lava.ogg",
 "sounds/liquid/lavapop.ogg",
 "sounds/liquid/splash.ogg",
 "sounds/liquid/splash2.ogg",
 "sounds/liquid/swim1.ogg",
 "sounds/liquid/swim10.ogg",
 "sounds/liquid/swim11.ogg",
 "sounds/liquid/swim12.ogg",
 "sounds/liquid/swim13.ogg",
 "sounds/liquid/swim14.ogg",
 "sounds/liquid/swim15.ogg",
 "sounds/liquid/swim16.ogg",
 "sounds/liquid/swim17.ogg",
 "sounds/liquid/swim18.ogg",
 "sounds/liquid/swim2.ogg",
 "sounds/liquid/swim3.ogg",
 "sounds/liquid/swim4.ogg",
 "sounds/liquid/swim5.ogg",
 "sounds/liquid/swim6.ogg",
 "sounds/liquid/swim7.ogg",
 "sounds/liquid/swim8.ogg",
 "sounds/liquid/swim9.ogg",
 "sounds/liquid/underwater_ambience.ogg",
 "sounds/liquid/water.ogg",
 "sounds/mob/axolotl/attack1.ogg",
 "sounds/mob/axolotl/attack2.ogg",
 "sounds/mob/axolotl/attack3.ogg",
 "sounds/mob/axolotl/attack4.ogg",
 "sounds/mob/axolotl/death1.ogg",
 "sounds/mob/axolotl/death2.ogg",
 "sounds/mob/axolotl/hurt1.ogg",
 "sounds/mob/axolotl/hurt2.ogg",
 "sounds/mob/axolotl/hurt3.ogg",
 "sounds/mob/axolotl/hurt4.ogg",
 "sounds/mob/axolotl/idle1.ogg",
 "sounds/mob/axolotl/idle2.ogg",
 "sounds/mob/axolotl/idle3.ogg",
 "sounds/mob/axolotl/idle4.ogg",
 "sounds/mob/axolotl/idle5.ogg",
 "sounds/mob/axolotl/idle_air1.ogg",
 "sounds/mob/axolotl/idle_air2.ogg",
 "sounds/mob/axolotl/idle_air3.ogg",
 "sounds/mob/axolotl/idle_air4.ogg",
 "sounds/mob/axolotl/idle_air5.ogg",
 "sounds/mob/bat/death.ogg",
 "sounds/mob/bat/hurt1.ogg",
 "sounds/mob/bat/hurt2.ogg",
 "sounds/mob/bat/hurt3.ogg",
 "sounds/mob/bat/hurt4.ogg",
 "sounds/mob/bat/idle1.ogg",
 "sounds/mob/bat/idle2.ogg",
 "sounds/mob/bat/idle3.ogg",
 "sounds/mob/bat/idle4.ogg",
 "sounds/mob/bat/loop.ogg",
 "sounds/mob/bat/takeoff.ogg",
 "sounds/mob/bee/aggressive1.ogg",
 "sounds/mob/bee/aggressive2.ogg",
 "sounds/mob/bee/aggressive3.ogg",
 "sounds/mob/bee/death1.ogg",
 "sounds/mob/bee/death2.ogg",
 "sounds/mob/bee/hurt1.ogg",
 "sounds/mob/bee/hurt2.ogg",
 "sounds/mob/bee/hurt3.ogg",
 "sounds/mob/bee/loop1.ogg",
 "sounds/mob/bee/loop2.ogg",
 "sounds/mob/bee/loop3.ogg",
 "sounds/mob/bee/loop4.ogg",
 "sounds/mob/bee/loop5.ogg",
 "sounds/mob/bee/pollinate1.ogg",
 "sounds/mob/bee/pollinate2.ogg",
 "sounds/mob/bee/pollinate3.ogg",
 "sounds/mob/bee/pollinate4.ogg",
 "sounds/mob/bee/sting.ogg",
 "sounds/mob/blaze/breathe1.ogg",
 "sounds/mob/blaze/breathe2.ogg",
 "sounds/mob/blaze/breathe3.ogg",
 "sounds/mob/blaze/breathe4.ogg",
 "sounds/mob/blaze/death.ogg",
 "sounds/mob/blaze/hit1.ogg",
 "sounds/mob/blaze/hit2.ogg",
 "sounds/mob/blaze/hit3.ogg",
 "sounds/mob/blaze/hit4.ogg",
 "sounds/mob/cat/beg1.ogg",
 "sounds/mob/cat/beg2.ogg",
 "sounds/mob/cat/beg3.ogg",
 "sounds/mob/cat/eat1.ogg",
 "sounds/mob/cat/eat2.ogg",
 "sounds/mob/cat/hiss1.ogg",
 "sounds/mob/cat/hiss2.ogg",
 "sounds/mob/cat/hiss3.ogg",
 "sounds/mob/cat/hitt1.ogg",
 "sounds/mob/cat/hitt2.ogg",
 "sounds/mob/cat/hitt3.ogg",
 "sounds/mob/cat/meow1.ogg",
 "sounds/mob/cat/meow2.ogg",
 "sounds/mob/cat/meow3.ogg",
 "sounds/mob/cat/meow4.ogg",
 "sounds/mob/cat/ocelot/death1.ogg",
 "sounds/mob/cat/ocelot/death2.ogg",
 "sounds/mob/cat/ocelot/death3.ogg",
 "sounds/mob/cat/ocelot/idle1.ogg",
 "sounds/mob/cat/ocelot/idle2.ogg",
 "sounds/mob/cat/ocelot/idle3.ogg",
 "sounds/mob/cat/ocelot/idle4.ogg",
 "sounds/mob/cat/purr1.ogg",
 "sounds/mob/cat/purr2.ogg",
 "sounds/mob/cat/purr3.ogg",
 "sounds/mob/cat/purreow1.ogg",
 "sounds/mob/cat/purreow2.ogg",
 "sounds/mob/cat/stray/idle1.ogg",
 "sounds/mob/cat/stray/idle2.ogg",
 "sounds/mob/cat/stray/idle3.ogg",
 "sounds/mob/cat/stray/idle4.ogg",
 "sounds/mob/chicken/hurt1.ogg",
 "sounds/mob/chicken/hurt2.ogg",
 "sounds/mob/chicken/plop.ogg",
 "sounds/mob/chicken/say1.ogg",
 "sounds/mob/chicken/say2.ogg",
 "sounds/mob/chicken/say3.ogg",
 "sounds/mob/chicken/step1.ogg",
 "sounds/mob/chicken/step2.ogg",
 "sounds/mob/cow/hurt1.ogg",
 "sounds/mob/cow/hurt2.ogg",
 "sounds/mob/cow/hurt3.ogg",
 "sounds/mob/cow/say1.ogg",
 "sounds/mob/cow/say2.ogg",
 "sounds/mob/cow/say3.ogg",
 "sounds/mob/cow/say4.ogg",
 "sounds/mob/cow/step1.ogg",
 "sounds/mob/cow/step2.ogg",
 "sounds/mob/cow/step3.ogg",
 "sounds/mob/cow/step4.ogg",
 "sounds/mob/creeper/death.ogg",
 "sounds/mob/creeper/say1.ogg",
 "sounds/mob/creeper/say2.ogg",
 "sounds/mob/creeper/say3.ogg",
 "sounds/mob/creeper/say4.ogg",
 "sounds/mob/dolphin/attack1.ogg",
 "sounds/mob/dolphin/attack2.ogg",
 "sounds/mob/dolphin/attack3.ogg",
 "sounds/mob/dolphin/blowhole1.ogg",
 "sounds/mob/dolphin/blowhole2.ogg",
 "sounds/mob/dolphin/death1.ogg",
 "sounds/mob/dolphin/death2.ogg",
 "sounds/mob/dolphin/eat1.ogg",
 "sounds/mob/dolphin/eat2.ogg",
 "sounds/mob/dolphin/eat3.ogg",
 "sounds/mob/dolphin/hurt1.ogg",
 "sounds/mob/dolphin/hurt2.ogg",
 "sounds/mob/dolphin/hurt3.ogg",
 "sounds/mob/dolphin/idle1.ogg",
 "sounds/mob/dolphin/idle2.ogg",
 "sounds/mob/dolphin/idle3.ogg",
 "sounds/mob/dolphin/idle4.ogg",
 "sounds/mob/dolphin/idle5.ogg",
 "sounds/mob/dolphin/idle6.ogg",
 "sounds/mob/dolphin/idle_water1.ogg",
 "sounds/mob/dolphin/idle_water10.ogg",
 "sounds/mob/dolphin/idle_water2.ogg",
 "sounds/mob/dolphin/idle_water3.ogg",
 "sounds/mob/dolphin/idle_water4.ogg",
 "sounds/mob/dolphin/idle_water5.ogg",
 "sounds/mob/dolphin/idle_water6.ogg",
 "sounds/mob/dolphin/idle_water7.ogg",
 "sounds/mob/dolphin/idle_water8.ogg",
 "sounds/mob/dolphin/idle_water9.ogg",
 "sounds/mob/dolphin/jump1.ogg",
 "sounds/mob/dolphin/jump2.ogg",
 "sounds/mob/dolphin/jump3.ogg",
 "sounds/mob/dolphin/play1.ogg",
 "sounds/mob/dolphin/play2.ogg",
 "sounds/mob/dolphin/splash1.ogg",
 "sounds/mob/dolphin/splash2.ogg",
 "sounds/mob/dolphin/splash3.ogg",
 "sounds/mob/dolphin/swim1.ogg",
 "sounds/mob/dolphin/swim2.ogg",
 "sounds/mob/dolphin/swim3.ogg",
 "sounds/mob/dolphin/swim4.ogg",
 "sounds/mob/drowned/convert1.ogg",
 "sounds/mob/drowned/convert2.ogg",
 "sounds/mob/drowned/convert3.ogg",
 "sounds/mob/drowned/death1.ogg",
 "sounds/mob/drowned/death2.ogg",
 "sounds/mob/drowned/hurt1.ogg",
 "sounds/mob/drowned/hurt2.ogg",
 "sounds/mob/drowned/hurt3.ogg",
 "sounds/mob/drowned/idle1.ogg",
 "sounds/mob/drowned/idle2.ogg",
 "sounds/mob/drowned/idle3.ogg",
 "sounds/mob/drowned/idle4.ogg",
 "sounds/mob/drowned/idle5.ogg",
 "sounds/mob/drowned/step1.ogg",
 "sounds/mob/drowned/step2.ogg",
 "sounds/mob/drowned/step3.ogg",
 "sounds/mob/drowned/step4.ogg",
 "sounds/mob/drowned/step5.ogg",
 "sounds/mob/drowned/water/death1.ogg",
 "sounds/mob/drowned/water/death2.ogg",
 "sounds/mob/drowned/water/hurt1.ogg",
 "sounds/mob/drowned/water/hurt2.ogg",
 "sounds/mob/drowned/water/hurt3.ogg",
 "sounds/mob/drowned/water/idle1.ogg",
 "sounds/mob/drowned/water/idle2.ogg",
 "sounds/mob/drowned/water/idle3.ogg",
 "sounds/mob/drowned/water/idle4.ogg",
 "sounds/mob/enderdragon/end.ogg",
 "sounds/mob/enderdragon/growl1.ogg",
 "sounds/mob/enderdragon/growl2.ogg",
 "sounds/mob/enderdragon/growl3.ogg",
 "sounds/mob/enderdragon/growl4.ogg",
 "sounds/mob/enderdragon/hit1.ogg",
 "sounds/mob/enderdragon/hit2.ogg",
 "sounds/mob/enderdragon/hit3.ogg",
 "sounds/mob/enderdragon/hit4.ogg",
 "sounds/mob/enderdragon/wings1.ogg",
 "sounds/mob/enderdragon/wings2.ogg",
 "sounds/mob/enderdragon/wings3.ogg",
 "sounds/mob/enderdragon/wings4.ogg",
 "sounds/mob/enderdragon/wings5.ogg",
 "sounds/mob/enderdragon/wings6.ogg",
 "sounds/mob/endermen/death.ogg",
 "sounds/mob/endermen/hit1.ogg",
 "sounds/mob/endermen/hit2.ogg",
 "sounds/mob/endermen/hit3.ogg",
 "sounds/mob/endermen/hit4.ogg",
 "sounds/mob/endermen/idle1.ogg",
 "sounds/mob/endermen/idle2.ogg",
 "sounds/mob/endermen/idle3.ogg",
 "sounds/mob/endermen/idle4.ogg",
 "sounds/mob/endermen/idle5.ogg",
 "sounds/mob/endermen/portal.ogg",
 "sounds/mob/endermen/portal2.ogg",
 "sounds/mob/endermen/scream1.ogg",
 "sounds/mob/endermen/scream2.ogg",
 "sounds/mob/endermen/scream3.ogg",
 "sounds/mob/endermen/scream4.ogg",
 "sounds/mob/endermen/stare.ogg",
 "sounds/mob/evocation_illager/cast1.ogg",
 "sounds/mob/evocation_illager/cast2.ogg",
 "sounds/mob/evocation_illager/celebrate.ogg",
 "sounds/mob/evocation_illager/death1.ogg",
 "sounds/mob/evocation_illager/death2.ogg",
 "sounds/mob/evocation_illager/fangs.ogg",
 "sounds/mob/evocation_illager/hurt1.ogg",
 "sounds/mob/evocation_illager/hurt2.ogg",
 "sounds/mob/evocation_illager/idle1.ogg",
 "sounds/mob/evocation_illager/idle2.ogg",
 "sounds/mob/evocation_illager/idle3.ogg",
 "sounds/mob/evocation_illager/idle4.ogg",
 "sounds/mob/evocation_illager/prepare_attack1.ogg",
 "sounds/mob/evocation_illager/prepare_attack2.ogg",
 "sounds/mob/evocation_illager/prepare_summon.ogg",
 "sounds/mob/evocation_illager/prepare_wololo.ogg",
 "sounds/mob/fox/aggro1.ogg",
 "sounds/mob/fox/aggro2.ogg",
 "sounds/mob/fox/aggro3.ogg",
 "sounds/mob/fox/aggro4.ogg",
 "sounds/mob/fox/aggro5.ogg",
 "sounds/mob/fox/aggro6.ogg",
 "sounds/mob/fox/aggro7.ogg",
 "sounds/mob/fox/bite1.ogg",
 "sounds/mob/fox/bite2.ogg",
 "sounds/mob/fox/bite3.ogg",
 "sounds/mob/fox/death1.ogg",
 "sounds/mob/fox/death2.ogg",
 "sounds/mob/fox/eat1.ogg",
 "sounds/mob/fox/eat2.ogg",
 "sounds/mob/fox/eat3.ogg",
 "sounds/mob/fox/hurt1.ogg",
 "sounds/mob/fox/hurt2.ogg",
 "sounds/mob/fox/hurt3.ogg",
 "sounds/mob/fox/hurt4.ogg",
 "sounds/mob/fox/idle1.ogg",
 "sounds/mob/fox/idle2.ogg",
 "sounds/mob/fox/idle3.ogg",
 "sounds/mob/fox/idle4.ogg",
 "sounds/mob/fox/idle5.ogg",
 "sounds/mob/fox/idle6.ogg",
 "sounds/mob/fox/screech1.ogg",
 "sounds/mob/fox/screech2.ogg",
 "sounds/mob/fox/screech3.ogg",
 "sounds/mob/fox/screech4.ogg",
 "sounds/mob/fox/sleep1.ogg",
 "sounds/mob/fox/sleep2.ogg",
 "sounds/mob/fox/sleep3.ogg",
 "sounds/mob/fox/sleep4.ogg",
 "sounds/mob/fox/sleep5.ogg",
 "sounds/mob/fox/sniff1.ogg",
 "sounds/mob/fox/sniff2.ogg",
 "sounds/mob/fox/sniff3.ogg",
 "sounds/mob/fox/sniff4.ogg",
 "sounds/mob/fox/spit1.ogg",
 "sounds/mob/fox/spit2.ogg",
 "sounds/mob/fox/spit3.ogg",
 "sounds/mob/ghast/affectionate_scream.ogg",
 "sounds/mob/ghast/charge.ogg",
 "sounds/mob/ghast/death.ogg",
 "sounds/mob/ghast/fireball4.ogg",
 "sounds/mob/ghast/moan1.ogg",
 "sounds/mob/ghast/moan2.ogg",
 "sounds/mob/ghast/moan3.ogg",
 "sounds/mob/ghast/moan4.ogg",
 "sounds/mob/ghast/moan5.ogg",
 "sounds/mob/ghast/moan6.ogg",
 "sounds/mob/ghast/moan7.ogg",
 "sounds/mob/ghast/scream1.ogg",
 "sounds/mob/ghast/scream2.ogg",
 "sounds/mob/ghast/scream3.ogg",
 "sounds/mob/ghast/scream4.ogg",
 "sounds/mob/ghast/scream5.ogg",
 "sounds/mob/goat/death1.ogg",
 "sounds/mob/goat/death2.ogg",
 "sounds/mob/goat/death3.ogg",
 "sounds/mob/goat/death4.ogg",
 "sounds/mob/goat/death5.ogg",
 "sounds/mob/goat/eat1.ogg",
 "sounds/mob/goat/eat2.ogg",
 "sounds/mob/goat/eat3.ogg",
 "sounds/mob/goat/hurt1.ogg",
 "sounds/mob/goat/hurt2.ogg",
 "sounds/mob/goat/hurt3.ogg",
 "sounds/mob/goat/hurt4.ogg",
 "sounds/mob/goat/idle1.ogg",
 "sounds/mob/goat/idle2.ogg",
 "sounds/mob/goat/idle3.ogg",
 "sounds/mob/goat/idle4.ogg",
 "sounds/mob/goat/idle5.ogg",
 "sounds/mob/goat/idle6.ogg",
 "sounds/mob/goat/idle7.ogg",
 "sounds/mob/goat/idle8.ogg",
 "sounds/mob/goat/impact1.ogg",
 "sounds/mob/goat/impact2.ogg",
 "sounds/mob/goat/impact3.ogg",
 "sounds/mob/goat/jump1.ogg",
 "sounds/mob/goat/jump2.ogg",
 "sounds/mob/goat/pre_ram1.ogg",
 "sounds/mob/goat/pre_ram2.ogg",
 "sounds/mob/goat/pre_ram3.ogg",
 "sounds/mob/goat/pre_ram4.ogg",
 "sounds/mob/goat/scream1.ogg",
 "sounds/mob/goat/scream2.ogg",
 "sounds/mob/goat/scream3.ogg",
 "sounds/mob/goat/scream4.ogg",
 "sounds/mob/goat/scream5.ogg",
 "sounds/mob/goat/scream6.ogg",
 "sounds/mob/goat/scream7.ogg",
 "sounds/mob/goat/scream8.ogg",
 "sounds/mob/goat/scream9.ogg",
 "sounds/mob/goat/screaming_death1.ogg",
 "sounds/mob/goat/screaming_death2.ogg",
 "sounds/mob/goat/screaming_death3.ogg",
 "sounds/mob/goat/screaming_hurt1.ogg",
 "sounds/mob/goat/screaming_hurt2.ogg",
 "sounds/mob/goat/screaming_hurt3.ogg",
 "sounds/mob/goat/screaming_milk1.ogg",
 "sounds/mob/goat/screaming_milk2.ogg",
 "sounds/mob/goat/screaming_milk3.ogg",
 "sounds/mob/goat/screaming_milk4.ogg",
 "sounds/mob/goat/screaming_milk5.ogg",
 "sounds/mob/goat/screaming_pre_ram1.ogg",
 "sounds/mob/goat/screaming_pre_ram2.ogg",
 "sounds/mob/goat/screaming_pre_ram3.ogg",
 "sounds/mob/goat/screaming_pre_ram4.ogg",
 "sounds/mob/goat/screaming_pre_ram5.ogg",
 "sounds/mob/goat/step1.ogg",
 "sounds/mob/goat/step2.ogg",
 "sounds/mob/goat/step3.ogg",
 "sounds/mob/goat/step4.ogg",
 "sounds/mob/goat/step5.ogg",
 "sounds/mob/goat/step6.ogg",
 "sounds/mob/guardian/attack_loop.ogg",
 "sounds/mob/guardian/curse.ogg",
 "sounds/mob/guardian/elder_death.ogg",
 "sounds/mob/guardian/elder_hit1.ogg",
 "sounds/mob/guardian/elder_hit2.ogg",
 "sounds/mob/guardian/elder_hit3.ogg",
 "sounds/mob/guardian/elder_hit4.ogg",
 "sounds/mob/guardian/elder_idle1.ogg",
 "sounds/mob/guardian/elder_idle2.ogg",
 "sounds/mob/guardian/elder_idle3.ogg",
 "sounds/mob/guardian/elder_idle4.ogg",
 "sounds/mob/guardian/flop1.ogg",
 "sounds/mob/guardian/flop2.ogg",
 "sounds/mob/guardian/flop3.ogg",
 "sounds/mob/guardian/flop4.ogg",
 "sounds/mob/guardian/guardian_death.ogg",
 "sounds/mob/guardian/guardian_hit1.ogg",
 "sounds/mob/guardian/guardian_hit2.ogg",
 "sounds/mob/guardian/guardian_hit3.ogg",
 "sounds/mob/guardian/guardian_hit4.ogg",
 "sounds/mob/guardian/land_death.ogg",
 "sounds/mob/guardian/land_hit1.ogg",
 "sounds/mob/guardian/land_hit2.ogg",
 "sounds/mob/guardian/land_hit3.ogg",
 "sounds/mob/guardian/land_hit4.ogg",
 "sounds/mob/guardian/land_idle1.ogg",
 "sounds/mob/guardian/land_idle2.ogg",
 "sounds/mob/guardian/land_idle3.ogg",
 "sounds/mob/guardian/land_idle4.ogg",
 "sounds/mob/hoglin/angry1.ogg",
 "sounds/mob/hoglin/angry2.ogg",
 "sounds/mob/hoglin/angry3.ogg",
 "sounds/mob/hoglin/angry4.ogg",
 "sounds/mob/hoglin/angry5.ogg",
 "sounds/mob/hoglin/angry6.ogg",
 "sounds/mob/hoglin/attack1.ogg",
 "sounds/mob/hoglin/attack2.ogg",
 "sounds/mob/hoglin/converted1.ogg",
 "sounds/mob/hoglin/converted2.ogg",
 "sounds/mob/hoglin/death1.ogg",
 "sounds/mob/hoglin/death2.ogg",
 "sounds/mob/hoglin/death3.ogg",
 "sounds/mob/hoglin/hurt1.ogg",
 "sounds/mob/hoglin/hurt2.ogg",
 "sounds/mob/hoglin/hurt3.ogg",
 "sounds/mob/hoglin/hurt4.ogg",
 "sounds/mob/hoglin/idle1.ogg",
 "sounds/mob/hoglin/idle10.ogg",
 "sounds/mob/hoglin/idle11.ogg",
 "sounds/mob/hoglin/idle2.ogg",
 "sounds/mob/hoglin/idle3.ogg",
 "sounds/mob/hoglin/idle4.ogg",
 "sounds/mob/hoglin/idle5.ogg",
 "sounds/mob/hoglin/idle6.ogg",
 "sounds/mob/hoglin/idle7.ogg",
 "sounds/mob/hoglin/idle8.ogg",
 "sounds/mob/hoglin/idle9.ogg",
 "sounds/mob/hoglin/retreat1.ogg",
 "sounds/mob/hoglin/retreat2.ogg",
 "sounds/mob/hoglin/retreat3.ogg",
 "sounds/mob/hoglin/step1.ogg",
 "sounds/mob/hoglin/step2.ogg",
 "sounds/mob/hoglin/step3.ogg",
 "sounds/mob/hoglin/step4.ogg",
 "sounds/mob/hoglin/step5.ogg",
 "sounds/mob/hoglin/step6.ogg",
 "sounds/mob/horse/angry1.ogg",
 "sounds/mob/horse/armor.ogg",
 "sounds/mob/horse/breathe1.ogg",
 "sounds/mob/horse/breathe2.ogg",
 "sounds/mob/horse/breathe3.ogg",
 "sounds/mob/horse/death.ogg",
 "sounds/mob/horse/donkey/angry1.ogg",
 "sounds/mob/horse/donkey/angry2.ogg",
 "sounds/mob/horse/donkey/death.ogg",
 "sounds/mob/horse/donkey/hit1.ogg",
 "sounds/mob/horse/donkey/hit2.ogg",
 "sounds/mob/horse/donkey/hit3.ogg",
 "sounds/mob/horse/donkey/idle1.ogg",
 "sounds/mob/horse/donkey/idle2.ogg",
 "sounds/mob/horse/donkey/idle3.ogg",
 "sounds/mob/horse/gallop1.ogg",
 "sounds/mob/horse/gallop2.ogg",
 "sounds/mob/horse/gallop3.ogg",
 "sounds/mob/horse/gallop4.ogg",
 "sounds/mob/horse/hit1.ogg",
 "sounds/mob/horse/hit2.ogg",
 "sounds/mob/horse/hit3.ogg",
 "sounds/mob/horse/hit4.ogg",
 "sounds/mob/horse/idle1.ogg",
 "sounds/mob/horse/idle2.ogg",
 "sounds/mob/horse/idle3.ogg",
 "sounds/mob/horse/jump.ogg",
 "sounds/mob/horse/land.ogg",
 "sounds/mob/horse/leather.ogg",
 "sounds/mob/horse/skeleton/death.ogg",
 "sounds/mob/horse/skeleton/hit1.ogg",
 "sounds/mob/horse/skeleton/hit2.ogg",
 "sounds/mob/horse/skeleton/hit3.ogg",
 "sounds/mob/horse/skeleton/hit4.ogg",
 "sounds/mob/horse/skeleton/idle1.ogg",
 "sounds/mob/horse/skeleton/idle2.ogg",
 "sounds/mob/horse/skeleton/idle3.ogg",
 "sounds/mob/horse/skeleton/water/gallop1.ogg",
 "sounds/mob/horse/skeleton/water/gallop2.ogg",
 "sounds/mob/horse/skeleton/water/gallop3.ogg",
 "sounds/mob/horse/skeleton/water/gallop4.ogg",
 "sounds/mob/horse/skeleton/water/idle1.ogg",
 "sounds/mob/horse/skeleton/water/idle2.ogg",
 "sounds/mob/horse/skeleton/water/idle3.ogg",
 "sounds/mob/horse/skeleton/water/idle4.ogg",
 "sounds/mob/horse/skeleton/water/idle5.ogg",
 "sounds/mob/horse/skeleton/water/jump.ogg",
 "sounds/mob/horse/skeleton/water/soft1.ogg",
 "sounds/mob/horse/skeleton/water/soft2.ogg",
 "sounds/mob/horse/skeleton/water/soft3.ogg",
 "sounds/mob/horse/skeleton/water/soft4.ogg",
 "sounds/mob/horse/skeleton/water/soft5.ogg",
 "sounds/mob/horse/skeleton/water/soft6.ogg",
 "sounds/mob/horse/soft1.ogg",
 "sounds/mob/horse/soft2.ogg",
 "sounds/mob/horse/soft3.ogg",
 "sounds/mob/horse/soft4.ogg",
 "sounds/mob/horse/soft5.ogg",
 "sounds/mob/horse/soft6.ogg",
 "sounds/mob/horse/wood1.ogg",
 "sounds/mob/horse/wood2.ogg",
 "sounds/mob/horse/wood3.ogg",
 "sounds/mob/horse/wood4.ogg",
 "sounds/mob/horse/wood5.ogg",
 "sounds/mob/horse/wood6.ogg",
 "sounds/mob/horse/zombie/death.ogg",
 "sounds/mob/horse/zombie/hit1.ogg",
 "sounds/mob/horse/zombie/hit2.ogg",
 "sounds/mob/horse/zombie/hit3.ogg",
 "sounds/mob/horse/zombie/hit4.ogg",
 "sounds/mob/horse/zombie/idle1.ogg",
 "sounds/mob/horse/zombie/idle2.ogg",
 "sounds/mob/horse/zombie/idle3.ogg",
 "sounds/mob/husk/convert1.ogg",
 "sounds/mob/husk/convert2.ogg",
 "sounds/mob/husk/death1.ogg",
 "sounds/mob/husk/death2.ogg",
 "sounds/mob/husk/hurt1.ogg",
 "sounds/mob/husk/hurt2.ogg",
 "sounds/mob/husk/idle1.ogg",
 "sounds/mob/husk/idle2.ogg",
 "sounds/mob/husk/idle3.ogg",
 "sounds/mob/husk/step1.ogg",
 "sounds/mob/husk/step2.ogg",
 "sounds/mob/husk/step3.ogg",
 "sounds/mob/husk/step4.ogg",
 "sounds/mob/husk/step5.ogg",
 "sounds/mob/illusion_illager/death1.ogg",
 "sounds/mob/illusion_illager/death2.ogg",
 "sounds/mob/illusion_illager/hurt1.ogg",
 "sounds/mob/illusion_illager/hurt2.ogg",
 "sounds/mob/illusion_illager/hurt3.ogg",
 "sounds/mob/illusion_illager/idle1.ogg",
 "sounds/mob/illusion_illager/idle2.ogg",
 "sounds/mob/illusion_illager/idle3.ogg",
 "sounds/mob/illusion_illager/idle4.ogg",
 "sounds/mob/illusion_illager/mirror_move1.ogg",
 "sounds/mob/illusion_illager/mirror_move2.ogg",
 "sounds/mob/illusion_illager/prepare_blind.ogg",
 "sounds/mob/illusion_illager/prepare_mirror.ogg",
 "sounds/mob/irongolem/damage1.ogg",
 "sounds/mob/irongolem/damage2.ogg",
 "sounds/mob/irongolem/death.ogg",
 "sounds/mob/irongolem/hit1.ogg",
 "sounds/mob/irongolem/hit2.ogg",
 "sounds/mob/irongolem/hit3.ogg",
 "sounds/mob/irongolem/hit4.ogg",
 "sounds/mob/irongolem/repair.ogg",
 "sounds/mob/irongolem/throw.ogg",
 "sounds/mob/irongolem/walk1.ogg",
 "sounds/mob/irongolem/walk2.ogg",
 "sounds/mob/irongolem/walk3.ogg",
 "sounds/mob/irongolem/walk4.ogg",
 "sounds/mob/llama/angry1.ogg",
 "sounds/mob/llama/death1.ogg",
 "sounds/mob/llama/death2.ogg",
 "sounds/mob/llama/eat1.ogg",
 "sounds/mob/llama/eat2.ogg",
 "sounds/mob/llama/eat3.ogg",
 "sounds/mob/llama/hurt1.ogg",
 "sounds/mob/llama/hurt2.ogg",
 "sounds/mob/llama/hurt3.ogg",
 "sounds/mob/llama/idle1.ogg",
 "sounds/mob/llama/idle2.ogg",
 "sounds/mob/llama/idle3.ogg",
 "sounds/mob/llama/idle4.ogg",
 "sounds/mob/llama/idle5.ogg",
 "sounds/mob/llama/spit1.ogg",
 "sounds/mob/llama/spit2.ogg",
 "sounds/mob/llama/step1.ogg",
 "sounds/mob/llama/step2.ogg",
 "sounds/mob/llama/step3.ogg",
 "sounds/mob/llama/step4.ogg",
 "sounds/mob/llama/step5.ogg",
 "sounds/mob/llama/swag.ogg",
 "sounds/mob/magmacube/big1.ogg",
 "sounds/mob/magmacube/big2.ogg",
 "sounds/mob/magmacube/big3.ogg",
 "sounds/mob/magmacube/big4.ogg",
 "sounds/mob/magmacube/jump1.ogg",
 "sounds/mob/magmacube/jump2.ogg",
 "sounds/mob/magmacube/jump3.ogg",
 "sounds/mob/magmacube/jump4.ogg",
 "sounds/mob/magmacube/small1.ogg",
 "sounds/mob/magmacube/small2.ogg",
 "sounds/mob/magmacube/small3.ogg",
 "sounds/mob/magmacube/small4.ogg",
 "sounds/mob/magmacube/small5.ogg",
 "sounds/mob/mooshroom/convert1.ogg",
 "sounds/mob/mooshroom/convert2.ogg",
 "sounds/mob/mooshroom/eat1.ogg",
 "sounds/mob/mooshroom/eat2.ogg",
 "sounds/mob/mooshroom/eat3.ogg",
 "sounds/mob/mooshroom/eat4.ogg",
 "sounds/mob/mooshroom/milk1.ogg",
 "sounds/mob/mooshroom/milk2.ogg",
 "sounds/mob/mooshroom/milk3.ogg",
 "sounds/mob/panda/aggressive/aggressive1.ogg",
 "sounds/mob/panda/aggressive/aggressive2.ogg",
 "sounds/mob/panda/aggressive/aggressive3.ogg",
 "sounds/mob/panda/aggressive/aggressive4.ogg",
 "sounds/mob/panda/bite1.ogg",
 "sounds/mob/panda/bite2.ogg",
 "sounds/mob/panda/bite3.ogg",
 "sounds/mob/panda/cant_breed1.ogg",
 "sounds/mob/panda/cant_breed2.ogg",
 "sounds/mob/panda/cant_breed3.ogg",
 "sounds/mob/panda/cant_breed4.ogg",
 "sounds/mob/panda/cant_breed5.ogg",
 "sounds/mob/panda/death1.ogg",
 "sounds/mob/panda/death2.ogg",
 "sounds/mob/panda/death3.ogg",
 "sounds/mob/panda/death4.ogg",
 "sounds/mob/panda/eat1.ogg",
 "sounds/mob/panda/eat10.ogg",
 "sounds/mob/panda/eat11.ogg",
 "sounds/mob/panda/eat12.ogg",
 "sounds/mob/panda/eat2.ogg",
 "sounds/mob/panda/eat3.ogg",
 "sounds/mob/panda/eat4.ogg",
 "sounds/mob/panda/eat5.ogg",
 "sounds/mob/panda/eat6.ogg",
 "sounds/mob/panda/eat7.ogg",
 "sounds/mob/panda/eat8.ogg",
 "sounds/mob/panda/eat9.ogg",
 "sounds/mob/panda/hurt1.ogg",
 "sounds/mob/panda/hurt2.ogg",
 "sounds/mob/panda/hurt3.ogg",
 "sounds/mob/panda/hurt4.ogg",
 "sounds/mob/panda/hurt5.ogg",
 "sounds/mob/panda/hurt6.ogg",
 "sounds/mob/panda/idle1.ogg",
 "sounds/mob/panda/idle2.ogg",
 "sounds/mob/panda/idle3.ogg",
 "sounds/mob/panda/idle4.ogg",
 "sounds/mob/panda/nosebreath1.ogg",
 "sounds/mob/panda/nosebreath2.ogg",
 "sounds/mob/panda/nosebreath3.ogg",
 "sounds/mob/panda/pant1.ogg",
 "sounds/mob/panda/pant2.ogg",
 "sounds/mob/panda/pre_sneeze.ogg",
 "sounds/mob/panda/sneeze1.ogg",
 "sounds/mob/panda/sneeze2.ogg",
 "sounds/mob/panda/sneeze3.ogg",
 "sounds/mob/panda/step1.ogg",
 "sounds/mob/panda/step2.ogg",
 "sounds/mob/panda/step3.ogg",
 "sounds/mob/panda/step4.ogg",
 "sounds/mob/panda/step5.ogg",
 "sounds/mob/panda/worried/worried1.ogg",
 "sounds/mob/panda/worried/worried2.ogg",
 "sounds/mob/panda/worried/worried3.ogg",
 "sounds/mob/panda/worried/worried4.ogg",
 "sounds/mob/panda/worried/worried5.ogg",
 "sounds/mob/panda/worried/worried6.ogg",
 "sounds/mob/parrot/death1.ogg",
 "sounds/mob/parrot/death2.ogg",
 "sounds/mob/parrot/death3.ogg",
 "sounds/mob/parrot/death4.ogg",
 "sounds/mob/parrot/eat1.ogg",
 "sounds/mob/parrot/eat2.ogg",
 "sounds/mob/parrot/eat3.ogg",
 "sounds/mob/parrot/fly1.ogg",
 "sounds/mob/parrot/fly2.ogg",
 "sounds/mob/parrot/fly3.ogg",
 "sounds/mob/parrot/fly4.ogg",
 "sounds/mob/parrot/fly5.ogg",
 "sounds/mob/parrot/fly6.ogg",
 "sounds/mob/parrot/fly7.ogg",
 "sounds/mob/parrot/fly8.ogg",
 "sounds/mob/parrot/hurt1.ogg",
 "sounds/mob/parrot/hurt2.ogg",
 "sounds/mob/parrot/idle1.ogg",
 "sounds/mob/parrot/idle2.ogg",
 "sounds/mob/parrot/idle3.ogg",
 "sounds/mob/parrot/idle4.ogg",
 "sounds/mob/parrot/idle5.ogg",
 "sounds/mob/parrot/idle6.ogg",
 "sounds/mob/parrot/step1.ogg",
 "sounds/mob/parrot/step2.ogg",
 "sounds/mob/parrot/step3.ogg",
 "sounds/mob/parrot/step4.ogg",
 "sounds/mob/parrot/step5.ogg",
 "sounds/mob/phantom/bite1.ogg",
 "sounds/mob/phantom/bite2.ogg",
 "sounds/mob/phantom/death1.ogg",
 "sounds/mob/phantom/death2.ogg",
 "sounds/mob/phantom/death3.ogg",
 "sounds/mob/phantom/flap1.ogg",
 "sounds/mob/phantom/flap2.ogg",
 "sounds/mob/phantom/flap3.ogg",
 "sounds/mob/phantom/flap4.ogg",
 "sounds/mob/phantom/flap5.ogg",
 "sounds/mob/phantom/flap6.ogg",
 "sounds/mob/phantom/hurt1.ogg",
 "sounds/mob/phantom/hurt2.ogg",
 "sounds/mob/phantom/hurt3.ogg",
 "sounds/mob/phantom/idle1.ogg",
 "sounds/mob/phantom/idle2.ogg",
 "sounds/mob/phantom/idle3.ogg",
 "sounds/mob/phantom/idle4.ogg",
 "sounds/mob/phantom/idle5.ogg",
 "sounds/mob/phantom/swoop1.ogg",
 "sounds/mob/phantom/swoop2.ogg",
 "sounds/mob/phantom/swoop3.ogg",
 "sounds/mob/phantom/swoop4.ogg",
 "sounds/mob/pig/death.ogg",
 "sounds/mob/pig/say1.ogg",
 "sounds/mob/pig/say2.ogg",
 "sounds/mob/pig/say3.ogg",
 "sounds/mob/pig/step1.ogg",
 "sounds/mob/pig/step2.ogg",
 "sounds/mob/pig/step3.ogg",
 "sounds/mob/pig/step4.ogg",
 "sounds/mob/pig/step5.ogg",
 "sounds/mob/piglin/admire1.ogg",
 "sounds/mob/piglin/admire2.ogg",
 "sounds/mob/piglin/angry1.ogg",
 "sounds/mob/piglin/angry2.ogg",
 "sounds/mob/piglin/angry3.ogg",
 "sounds/mob/piglin/angry4.ogg",
 "sounds/mob/piglin/celebrate1.ogg",
 "sounds/mob/piglin/celebrate2.ogg",
 "sounds/mob/piglin/celebrate3.ogg",
 "sounds/mob/piglin/celebrate4.ogg",
 "sounds/mob/piglin/converted1.ogg",
 "sounds/mob/piglin/converted2.ogg",
 "sounds/mob/piglin/death1.ogg",
 "sounds/mob/piglin/death2.ogg",
 "sounds/mob/piglin/death3.ogg",
 "sounds/mob/piglin/death4.ogg",
 "sounds/mob/piglin/hurt1.ogg",
 "sounds/mob/piglin/hurt2.ogg",
 "sounds/mob/piglin/hurt3.ogg",
 "sounds/mob/piglin/idle1.ogg",
 "sounds/mob/piglin/idle2.ogg",
 "sounds/mob/piglin/idle3.ogg",
 "sounds/mob/piglin/idle4.ogg",
 "sounds/mob/piglin/idle5.ogg",
 "sounds/mob/piglin/jealous1.ogg",
 "sounds/mob/piglin/jealous2.ogg",
 "sounds/mob/piglin/jealous3.ogg",
 "sounds/mob/piglin/jealous4.ogg",
 "sounds/mob/piglin/jealous5.ogg",
 "sounds/mob/piglin/retreat1.ogg",
 "sounds/mob/piglin/retreat2.ogg",
 "sounds/mob/piglin/retreat3.ogg",
 "sounds/mob/piglin/retreat4.ogg",
 "sounds/mob/piglin/step1.ogg",
 "sounds/mob/piglin/step2.ogg",
 "sounds/mob/piglin/step3.ogg",
 "sounds/mob/piglin/step4.ogg",
 "sounds/mob/piglin/step5.ogg",
 "sounds/mob/piglin_brute/angry1.ogg",
 "sounds/mob/piglin_brute/angry2.ogg",
 "sounds/mob/piglin_brute/angry3.ogg",
 "sounds/mob/piglin_brute/angry4.ogg",
 "sounds/mob/piglin_brute/angry5.ogg",
 "sounds/mob/piglin_brute/death1.ogg",
 "sounds/mob/piglin_brute/death2.ogg",
 "sounds/mob/piglin_brute/death3.ogg",
 "sounds/mob/piglin_brute/hurt1.ogg",
 "sounds/mob/piglin_brute/hurt2.ogg",
 "sounds/mob/piglin_brute/hurt3.ogg",
 "sounds/mob/piglin_brute/hurt4.ogg",
 "sounds/mob/piglin_brute/idle1.ogg",
 "sounds/mob/piglin_brute/idle2.ogg",
 "sounds/mob/piglin_brute/idle3.ogg",
 "sounds/mob/piglin_brute/idle4.ogg",
 "sounds/mob/piglin_brute/idle5.ogg",
 "sounds/mob/piglin_brute/idle6.ogg",
 "sounds/mob/piglin_brute/idle7.ogg",
 "sounds/mob/piglin_brute/idle8.ogg",
 "sounds/mob/piglin_brute/idle9.ogg",
 "sounds/mob/piglin_brute/step1.ogg",
 "sounds/mob/piglin_brute/step2.ogg",
 "sounds/mob/piglin_brute/step3.ogg",
 "sounds/mob/piglin_brute/step4.ogg",
 "sounds/mob/piglin_brute/step5.ogg",
 "sounds/mob/pillager/celebrate1.ogg",
 "sounds/mob/pillager/celebrate2.ogg",
 "sounds/mob/pillager/celebrate3.ogg",
 "sounds/mob/pillager/celebrate4.ogg",
 "sounds/mob/pillager/death1.ogg",
 "sounds/mob/pillager/death2.ogg",
 "sounds/mob/pillager/horn_celebrate.ogg",
 "sounds/mob/pillager/hurt1.ogg",
 "sounds/mob/pillager/hurt2.ogg",
 "sounds/mob/pillager/hurt3.ogg",
 "sounds/mob/pillager/idle1.ogg",
 "sounds/mob/pillager/idle2.ogg",
 "sounds/mob/pillager/idle3.ogg",
 "sounds/mob/pillager/idle4.ogg",
 "sounds/mob/polarbear/death1.ogg",
 "sounds/mob/polarbear/death2.ogg",
 "sounds/mob/polarbear/death3.ogg",
 "sounds/mob/polarbear/hurt1.ogg",
 "sounds/mob/polarbear/hurt2.ogg",
 "sounds/mob/polarbear/hurt3.ogg",
 "sounds/mob/polarbear/hurt4.ogg",
 "sounds/mob/polarbear/idle1.ogg",
 "sounds/mob/polarbear/idle2.ogg",
 "sounds/mob/polarbear/idle3.ogg",
 "sounds/mob/polarbear/idle4.ogg",
 "sounds/mob/polarbear/step1.ogg",
 "sounds/mob/polarbear/step2.ogg",
 "sounds/mob/polarbear/step3.ogg",
 "sounds/mob/polarbear/step4.ogg",
 "sounds/mob/polarbear/warning1.ogg",
 "sounds/mob/polarbear/warning2.ogg",
 "sounds/mob/polarbear/warning3.ogg",
 "sounds/mob/polarbear_baby/idle1.ogg",
 "sounds/mob/polarbear_baby/idle2.ogg",
 "sounds/mob/polarbear_baby/idle3.ogg",
 "sounds/mob/polarbear_baby/idle4.ogg",
 "sounds/mob/rabbit/bunnymurder.ogg",
 "sounds/mob/rabbit/hop1.ogg",
 "sounds/mob/rabbit/hop2.ogg",
 "sounds/mob/rabbit/hop3.ogg",
 "sounds/mob/rabbit/hop4.ogg",
 "sounds/mob/rabbit/hurt1.ogg",
 "sounds/mob/rabbit/hurt2.ogg",
 "sounds/mob/rabbit/hurt3.ogg",
 "sounds/mob/rabbit/hurt4.ogg",
 "sounds/mob/rabbit/idle1.ogg",
 "sounds/mob/rabbit/idle2.ogg",
 "sounds/mob/rabbit/idle3.ogg",
 "sounds/mob/rabbit/idle4.ogg",
 "sounds/mob/ravager/bite1.ogg",
 "sounds/mob/ravager/bite2.ogg",
 "sounds/mob/ravager/bite3.ogg",
 "sounds/mob/ravager/celebrate1.ogg",
 "sounds/mob/ravager/celebrate2.ogg",
 "sounds/mob/ravager/death1.ogg",
 "sounds/mob/ravager/death2.ogg",
 "sounds/mob/ravager/death3.ogg",
 "sounds/mob/ravager/hurt1.ogg",
 "sounds/mob/ravager/hurt2.ogg",
 "sounds/mob/ravager/hurt3.ogg",
 "sounds/mob/ravager/hurt4.ogg",
 "sounds/mob/ravager/idle1.ogg",
 "sounds/mob/ravager/idle2.ogg",
 "sounds/mob/ravager/idle3.ogg",
 "sounds/mob/ravager/idle4.ogg",
 "sounds/mob/ravager/idle5.ogg",
 "sounds/mob/ravager/idle6.ogg",
 "sounds/mob/ravager/idle7.ogg",
 "sounds/mob/ravager/idle8.ogg",
 "sounds/mob/ravager/roar1.ogg",
 "sounds/mob/ravager/roar2.ogg",
 "sounds/mob/ravager/roar3.ogg",
 "sounds/mob/ravager/roar4.ogg",
 "sounds/mob/ravager/step1.ogg",
 "sounds/mob/ravager/step2.ogg",
 "sounds/mob/ravager/step3.ogg",
 "sounds/mob/ravager/step4.ogg",
 "sounds/mob/ravager/step5.ogg",
 "sounds/mob/ravager/stun1.ogg",
 "sounds/mob/ravager/stun2.ogg",
 "sounds/mob/ravager/stun3.ogg",
 "sounds/mob/sheep/say1.ogg",
 "sounds/mob/sheep/say2.ogg",
 "sounds/mob/sheep/say3.ogg",
 "sounds/mob/sheep/shear.ogg",
 "sounds/mob/sheep/step1.ogg",
 "sounds/mob/sheep/step2.ogg",
 "sounds/mob/sheep/step3.ogg",
 "sounds/mob/sheep/step4.ogg",
 "sounds/mob/sheep/step5.ogg",
 "sounds/mob/silverfish/hit1.ogg",
 "sounds/mob/silverfish/hit2.ogg",
 "sounds/mob/silverfish/hit3.ogg",
 "sounds/mob/silverfish/kill.ogg",
 "sounds/mob/silverfish/say1.ogg",
 "sounds/mob/silverfish/say2.ogg",
 "sounds/mob/silverfish/say3.ogg",
 "sounds/mob/silverfish/say4.ogg",
 "sounds/mob/silverfish/step1.ogg",
 "sounds/mob/silverfish/step2.ogg",
 "sounds/mob/silverfish/step3.ogg",
 "sounds/mob/silverfish/step4.ogg",
 "sounds/mob/skeleton/death.ogg",
 "sounds/mob/skeleton/hurt1.ogg",
 "sounds/mob/skeleton/hurt2.ogg",
 "sounds/mob/skeleton/hurt3.ogg",
 "sounds/mob/skeleton/hurt4.ogg",
 "sounds/mob/skeleton/say1.ogg",
 "sounds/mob/skeleton/say2.ogg",
 "sounds/mob/skeleton/say3.ogg",
 "sounds/mob/skeleton/step1.ogg",
 "sounds/mob/skeleton/step2.ogg",
 "sounds/mob/skeleton/step3.ogg",
 "sounds/mob/skeleton/step4.ogg",
 "sounds/mob/slime/attack1.ogg",
 "sounds/mob/slime/attack2.ogg",
 "sounds/mob/slime/big1.ogg",
 "sounds/mob/slime/big2.ogg",
 "sounds/mob/slime/big3.ogg",
 "sounds/mob/slime/big4.ogg",
 "sounds/mob/slime/small1.ogg",
 "sounds/mob/slime/small2.ogg",
 "sounds/mob/slime/small3.ogg",
 "sounds/mob/slime/small4.ogg",
 "sounds/mob/slime/small5.ogg",
 "sounds/mob/spider/death.ogg",
 "sounds/mob/spider/say1.ogg",
 "sounds/mob/spider/say2.ogg",
 "sounds/mob/spider/say3.ogg",
 "sounds/mob/spider/say4.ogg",
 "sounds/mob/spider/step1.ogg",
 "sounds/mob/spider/step2.ogg",
 "sounds/mob/spider/step3.ogg",
 "sounds/mob/spider/step4.ogg",
 "sounds/mob/stray/convert1.ogg",
 "sounds/mob/stray/convert2.ogg",
 "sounds/mob/stray/convert3.ogg",
 "sounds/mob/stray/death1.ogg",
 "sounds/mob/stray/death2.ogg",
 "sounds/mob/stray/hurt1.ogg",
 "sounds/mob/stray/hurt2.ogg",
 "sounds/mob/stray/hurt3.ogg",
 "sounds/mob/stray/hurt4.ogg",
 "sounds/mob/stray/idle1.ogg",
 "sounds/mob/stray/idle2.ogg",
 "sounds/mob/stray/idle3.ogg",
 "sounds/mob/stray/idle4.ogg",
 "sounds/mob/stray/step1.ogg",
 "sounds/mob/stray/step2.ogg",
 "sounds/mob/stray/step3.ogg",
 "sounds/mob/stray/step4.ogg",
 "sounds/mob/strider/death1.ogg",
 "sounds/mob/strider/death2.ogg",
 "sounds/mob/strider/death3.ogg",
 "sounds/mob/strider/death4.ogg",
 "sounds/mob/strider/eat1.ogg",
 "sounds/mob/strider/eat2.ogg",
 "sounds/mob/strider/eat3.ogg",
 "sounds/mob/strider/happy1.ogg",
 "sounds/mob/strider/happy2.ogg",
 "sounds/mob/strider/happy3.ogg",
 "sounds/mob/strider/happy4.ogg",
 "sounds/mob/strider/happy5.ogg",
 "sounds/mob/strider/hurt1.ogg",
 "sounds/mob/strider/hurt2.ogg",
 "sounds/mob/strider/hurt3.ogg",
 "sounds/mob/strider/hurt4.ogg",
 "sounds/mob/strider/idle1.ogg",
 "sounds/mob/strider/idle2.ogg",
 "sounds/mob/strider/idle3.ogg",
 "sounds/mob/strider/idle4.ogg",
 "sounds/mob/strider/idle5.ogg",
 "sounds/mob/strider/idle6.ogg",
 "sounds/mob/strider/retreat1.ogg",
 "sounds/mob/strider/retreat2.ogg",
 "sounds/mob/strider/retreat3.ogg",
 "sounds/mob/strider/retreat4.ogg",
 "sounds/mob/strider/retreat5.ogg",
 "sounds/mob/strider/step1.ogg",
 "sounds/mob/strider/step2.ogg",
 "sounds/mob/strider/step3.ogg",
 "sounds/mob/strider/step4.ogg",
 "sounds/mob/strider/step5.ogg",
 "sounds/mob/strider/step_lava1.ogg",
 "sounds/mob/strider/step_lava2.ogg",
 "sounds/mob/strider/step_lava3.ogg",
 "sounds/mob/strider/step_lava4.ogg",
 "sounds/mob/strider/step_lava5.ogg",
 "sounds/mob/strider/step_lava6.ogg",
 "sounds/mob/turtle/armor.ogg",
 "sounds/mob/turtle/baby/death1.ogg",
 "sounds/mob/turtle/baby/death2.ogg",
 "sounds/mob/turtle/baby/egg_hatched1.ogg",
 "sounds/mob/turtle/baby/egg_hatched2.ogg",
 "sounds/mob/turtle/baby/egg_hatched3.ogg",
 "sounds/mob/turtle/baby/hurt1.ogg",
 "sounds/mob/turtle/baby/hurt2.ogg",
 "sounds/mob/turtle/baby/shamble1.ogg",
 "sounds/mob/turtle/baby/shamble2.ogg",
 "sounds/mob/turtle/baby/shamble3.ogg",
 "sounds/mob/turtle/baby/shamble4.ogg",
 "sounds/mob/turtle/death1.ogg",
 "sounds/mob/turtle/death2.ogg",
 "sounds/mob/turtle/death3.ogg",
 "sounds/mob/turtle/egg/drop_egg1.ogg",
 "sounds/mob/turtle/egg/drop_egg2.ogg",
 "sounds/mob/turtle/egg/egg_break1.ogg",
 "sounds/mob/turtle/egg/egg_break2.ogg",
 "sounds/mob/turtle/egg/egg_crack1.ogg",
 "sounds/mob/turtle/egg/egg_crack2.ogg",
 "sounds/mob/turtle/egg/egg_crack3.ogg",
 "sounds/mob/turtle/egg/egg_crack4.ogg",
 "sounds/mob/turtle/egg/egg_crack5.ogg",
 "sounds/mob/turtle/egg/jump_egg1.ogg",
 "sounds/mob/turtle/egg/jump_egg2.ogg",
 "sounds/mob/turtle/egg/jump_egg3.ogg",
 "sounds/mob/turtle/egg/jump_egg4.ogg",
 "sounds/mob/turtle/hurt1.ogg",
 "sounds/mob/turtle/hurt2.ogg",
 "sounds/mob/turtle/hurt3.ogg",
 "sounds/mob/turtle/hurt4.ogg",
 "sounds/mob/turtle/hurt5.ogg",
 "sounds/mob/turtle/idle1.ogg",
 "sounds/mob/turtle/idle2.ogg",
 "sounds/mob/turtle/idle3.ogg",
 "sounds/mob/turtle/swim/swim1.ogg",
 "sounds/mob/turtle/swim/swim2.ogg",
 "sounds/mob/turtle/swim/swim3.ogg",
 "sounds/mob/turtle/swim/swim4.ogg",
 "sounds/mob/turtle/swim/swim5.ogg",
 "sounds/mob/turtle/walk1.ogg",
 "sounds/mob/turtle/walk2.ogg",
 "sounds/mob/turtle/walk3.ogg",
 "sounds/mob/turtle/walk4.ogg",
 "sounds/mob/turtle/walk5.ogg",
 "sounds/mob/vex/charge1.ogg",
 "sounds/mob/vex/charge2.ogg",
 "sounds/mob/vex/charge3.ogg",
 "sounds/mob/vex/death1.ogg",
 "sounds/mob/vex/death2.ogg",
 "sounds/mob/vex/hurt1.ogg",
 "sounds/mob/vex/hurt2.ogg",
 "sounds/mob/vex/idle1.ogg",
 "sounds/mob/vex/idle2.ogg",
 "sounds/mob/vex/idle3.ogg",
 "sounds/mob/vex/idle4.ogg",
 "sounds/mob/villager/death.ogg",
 "sounds/mob/villager/haggle1.ogg",
 "sounds/mob/villager/haggle2.ogg",
 "sounds/mob/villager/haggle3.ogg",
 "sounds/mob/villager/hit1.ogg",
 "sounds/mob/villager/hit2.ogg",
 "sounds/mob/villager/hit3.ogg",
 "sounds/mob/villager/hit4.ogg",
 "sounds/mob/villager/idle1.ogg",
 "sounds/mob/villager/idle2.ogg",
 "sounds/mob/villager/idle3.ogg",
 "sounds/mob/villager/no1.ogg",
 "sounds/mob/villager/no2.ogg",
 "sounds/mob/villager/no3.ogg",
 "sounds/mob/villager/yes1.ogg",
 "sounds/mob/villager/yes2.ogg",
 "sounds/mob/villager/yes3.ogg",
 "sounds/mob/vindication_illager/celebrate1.ogg",
 "sounds/mob/vindication_illager/celebrate2.ogg",
 "sounds/mob/vindication_illager/death1.ogg",
 "sounds/mob/vindication_illager/death2.ogg",
 "sounds/mob/vindication_illager/hurt1.ogg",
 "sounds/mob/vindication_illager/hurt2.ogg",
 "sounds/mob/vindication_illager/hurt3.ogg",
 "sounds/mob/vindication_illager/idle1.ogg",
 "sounds/mob/vindication_illager/idle2.ogg",
 "sounds/mob/vindication_illager/idle3.ogg",
 "sounds/mob/vindication_illager/idle4.ogg",
 "sounds/mob/vindication_illager/idle5.ogg",
 "sounds/mob/wandering_trader/appeared1.ogg",
 "sounds/mob/wandering_trader/appeared2.ogg",
 "sounds/mob/wandering_trader/death.ogg",
 "sounds/mob/wandering_trader/disappeared1.ogg",
 "sounds/mob/wandering_trader/disappeared2.ogg",
 "sounds/mob/wandering_trader/drink_milk1.ogg",
 "sounds/mob/wandering_trader/drink_milk2.ogg",
 "sounds/mob/wandering_trader/drink_milk3.ogg",
 "sounds/mob/wandering_trader/drink_milk4.ogg",
 "sounds/mob/wandering_trader/drink_milk5.ogg",
 "sounds/mob/wandering_trader/drink_potion.ogg",
 "sounds/mob/wandering_trader/haggle1.ogg",
 "sounds/mob/wandering_trader/haggle2.ogg",
 "sounds/mob/wandering_trader/haggle3.ogg",
 "sounds/mob/wandering_trader/hurt1.ogg",
 "sounds/mob/wandering_trader/hurt2.ogg",
 "sounds/mob/wandering_trader/hurt3.ogg",
 "sounds/mob/wandering_trader/hurt4.ogg",
 "sounds/mob/wandering_trader/idle1.ogg",
 "sounds/mob/wandering_trader/idle2.ogg",
 "sounds/mob/wandering_trader/idle3.ogg",
 "sounds/mob/wandering_trader/idle4.ogg",
 "sounds/mob/wandering_trader/idle5.ogg",
 "sounds/mob/wandering_trader/no1.ogg",
 "sounds/mob/wandering_trader/no2.ogg",
 "sounds/mob/wandering_trader/no3.ogg",
 "sounds/mob/wandering_trader/no4.ogg",
 "sounds/mob/wandering_trader/no5.ogg",
 "sounds/mob/wandering_trader/reappeared1.ogg",
 "sounds/mob/wandering_trader/reappeared2.ogg",
 "sounds/mob/wandering_trader/yes1.ogg",
 "sounds/mob/wandering_trader/yes2.ogg",
 "sounds/mob/wandering_trader/yes3.ogg",
 "sounds/mob/wandering_trader/yes4.ogg",
 "sounds/mob/wither/death.ogg",
 "sounds/mob/wither/hurt1.ogg",
 "sounds/mob/wither/hurt2.ogg",
 "sounds/mob/wither/hurt3.ogg",
 "sounds/mob/wither/hurt4.ogg",
 "sounds/mob/wither/idle1.ogg",
 "sounds/mob/wither/idle2.ogg",
 "sounds/mob/wither/idle3.ogg",
 "sounds/mob/wither/idle4.ogg",
 "sounds/mob/wither/shoot.ogg",
 "sounds/mob/wither/spawn.ogg",
 "sounds/mob/wither_skeleton/death1.ogg",
 "sounds/mob/wither_skeleton/death2.ogg",
 "sounds/mob/wither_skeleton/hurt1.ogg",
 "sounds/mob/wither_skeleton/hurt2.ogg",
 "sounds/mob/wither_skeleton/hurt3.ogg",
 "sounds/mob/wither_skeleton/hurt4.ogg",
 "sounds/mob/wither_skeleton/idle1.ogg",
 "sounds/mob/wither_skeleton/idle2.ogg",
 "sounds/mob/wither_skeleton/idle3.ogg",
 "sounds/mob/wither_skeleton/step1.ogg",
 "sounds/mob/wither_skeleton/step2.ogg",
 "sounds/mob/wither_skeleton/step3.ogg",
 "sounds/mob/wither_skeleton/step4.ogg",
 "sounds/mob/wolf/bark1.ogg",
 "sounds/mob/wolf/bark2.ogg",
 "sounds/mob/wolf/bark3.ogg",
 "sounds/mob/wolf/death.ogg",
 "sounds/mob/wolf/growl1.ogg",
 "sounds/mob/wolf/growl2.ogg",
 "sounds/mob/wolf/growl3.ogg",
 "sounds/mob/wolf/howl1.ogg",
 "sounds/mob/wolf/howl2.ogg",
 "sounds/mob/wolf/hurt1.ogg",
 "sounds/mob/wolf/hurt2.ogg",
 "sounds/mob/wolf/hurt3.ogg",
 "sounds/mob/wolf/panting.ogg",
 "sounds/mob/wolf/shake.ogg",
 "sounds/mob/wolf/step1.ogg",
 "sounds/mob/wolf/step2.ogg",
 "sounds/mob/wolf/step3.ogg",
 "sounds/mob/wolf/step4.ogg",
 "sounds/mob/wolf/step5.ogg",
 "sounds/mob/wolf/whine.ogg",
 "sounds/mob/zoglin/angry1.ogg",
 "sounds/mob/zoglin/angry2.ogg",
 "sounds/mob/zoglin/angry3.ogg",
 "sounds/mob/zoglin/attack1.ogg",
 "sounds/mob/zoglin/attack2.ogg",
 "sounds/mob/zoglin/death1.ogg",
 "sounds/mob/zoglin/death2.ogg",
 "sounds/mob/zoglin/death3.ogg",
 "sounds/mob/zoglin/hurt1.ogg",
 "sounds/mob/zoglin/hurt2.ogg",
 "sounds/mob/zoglin/hurt3.ogg",
 "sounds/mob/zoglin/idle1.ogg",
 "sounds/mob/zoglin/idle2.ogg",
 "sounds/mob/zoglin/idle3.ogg",
 "sounds/mob/zoglin/idle4.ogg",
 "sounds/mob/zoglin/idle5.ogg",
 "sounds/mob/zoglin/idle6.ogg",
 "sounds/mob/zoglin/step1.ogg",
 "sounds/mob/zoglin/step2.ogg",
 "sounds/mob/zoglin/step3.ogg",
 "sounds/mob/zoglin/step4.ogg",
 "sounds/mob/zoglin/step5.ogg",
 "sounds/mob/zombie/death.ogg",
 "sounds/mob/zombie/hurt1.ogg",
 "sounds/mob/zombie/hurt2.ogg",
 "sounds/mob/zombie/infect.ogg",
 "sounds/mob/zombie/metal1.ogg",
 "sounds/mob/zombie/metal2.ogg",
 "sounds/mob/zombie/metal3.ogg",
 "sounds/mob/zombie/remedy.ogg",
 "sounds/mob/zombie/say1.ogg",
 "sounds/mob/zombie/say2.ogg",
 "sounds/mob/zombie/say3.ogg",
 "sounds/mob/zombie/step1.ogg",
 "sounds/mob/zombie/step2.ogg",
 "sounds/mob/zombie/step3.ogg",
 "sounds/mob/zombie/step4.ogg",
 "sounds/mob/zombie/step5.ogg",
 "sounds/mob/zombie/unfect.ogg",
 "sounds/mob/zombie/wood1.ogg",
 "sounds/mob/zombie/wood2.ogg",
 "sounds/mob/zombie/wood3.ogg",
 "sounds/mob/zombie/wood4.ogg",
 "sounds/mob/zombie/woodbreak.ogg",
 "sounds/mob/zombie_villager/death.ogg",
 "sounds/mob/zombie_villager/hurt1.ogg",
 "sounds/mob/zombie_villager/hurt2.ogg",
 "sounds/mob/zombie_villager/say1.ogg",
 "sounds/mob/zombie_villager/say2.ogg",
 "sounds/mob/zombie_villager/say3.ogg",
 "sounds/mob/zombified_piglin/zpig1.ogg",
 "sounds/mob/zombified_piglin/zpig2.ogg",
 "sounds/mob/zombified_piglin/zpig3.ogg",
 "sounds/mob/zombified_piglin/zpig4.ogg",
 "sounds/mob/zombified_piglin/zpigangry1.ogg",
 "sounds/mob/zombified_piglin/zpigangry2.ogg",
 "sounds/mob/zombified_piglin/zpigangry3.ogg",
 "sounds/mob/zombified_piglin/zpigangry4.ogg",
 "sounds/mob/zombified_piglin/zpigdeath.ogg",
 "sounds/mob/zombified_piglin/zpighurt1.ogg",
 "sounds/mob/zombified_piglin/zpighurt2.ogg",
 "sounds/random/anvil_break.ogg",
 "sounds/random/anvil_land.ogg",
 "sounds/random/anvil_use.ogg",
 "sounds/random/bow.ogg",
 "sounds/random/bowhit1.ogg",
 "sounds/random/bowhit2.ogg",
 "sounds/random/bowhit3.ogg",
 "sounds/random/bowhit4.ogg",
 "sounds/random/break.ogg",
 "sounds/random/breath.ogg",
 "sounds/random/burp.ogg",
 "sounds/random/chestclosed.ogg",
 "sounds/random/chestopen.ogg",
 "sounds/random/classic_hurt.ogg",
 "sounds/random/click.ogg",
 "sounds/random/click_stereo.ogg",
 "sounds/random/door_close.ogg",
 "sounds/random/door_open.ogg",
 "sounds/random/drink.ogg",
 "sounds/random/eat1.ogg",
 "sounds/random/eat2.ogg",
 "sounds/random/eat3.ogg",
 "sounds/random/explode1.ogg",
 "sounds/random/explode2.ogg",
 "sounds/random/explode3.ogg",
 "sounds/random/explode4.ogg",
 "sounds/random/fire.ogg",
 "sounds/random/fizz.ogg",
 "sounds/random/fuse.ogg",
 "sounds/random/ignite.ogg",
 "sounds/random/levelup.ogg",
 "sounds/random/orb.ogg",
 "sounds/random/pop.ogg",
 "sounds/random/splash.ogg",
 "sounds/random/successful_hit.ogg",
 "sounds/random/wood_click.ogg",
 "sounds/step/cloth1.ogg",
 "sounds/step/cloth2.ogg",
 "sounds/step/cloth3.ogg",
 "sounds/step/cloth4.ogg",
 "sounds/step/coral1.ogg",
 "sounds/step/coral2.ogg",
 "sounds/step/coral3.ogg",
 "sounds/step/coral4.ogg",
 "sounds/step/coral5.ogg",
 "sounds/step/coral6.ogg",
 "sounds/step/grass1.ogg",
 "sounds/step/grass2.ogg",
 "sounds/step/grass3.ogg",
 "sounds/step/grass4.ogg",
 "sounds/step/grass5.ogg",
 "sounds/step/grass6.ogg",
 "sounds/step/gravel1.ogg",
 "sounds/step/gravel2.ogg",
 "sounds/step/gravel3.ogg",
 "sounds/step/gravel4.ogg",
 "sounds/step/ladder1.ogg",
 "sounds/step/ladder2.ogg",
 "sounds/step/ladder3.ogg",
 "sounds/step/ladder4.ogg",
 "sounds/step/ladder5.ogg",
 "sounds/step/sand1.ogg",
 "sounds/step/sand2.ogg",
 "sounds/step/sand3.ogg",
 "sounds/step/sand4.ogg",
 "sounds/step/sand5.ogg",
 "sounds/step/scaffold1.ogg",
 "sounds/step/scaffold2.ogg",
 "sounds/step/scaffold3.ogg",
 "sounds/step/scaffold4.ogg",
 "sounds/step/scaffold5.ogg",
 "sounds/step/scaffold6.ogg",
 "sounds/step/scaffold7.ogg",
 "sounds/step/snow1.ogg",
 "sounds/step/snow2.ogg",
 "sounds/step/snow3.ogg",
 "sounds/step/snow4.ogg",
 "sounds/step/stone1.ogg",
 "sounds/step/stone2.ogg",
 "sounds/step/stone3.ogg",
 "sounds/step/stone4.ogg",
 "sounds/step/stone5.ogg",
 "sounds/step/stone6.ogg",
 "sounds/step/wet_grass1.ogg",
 "sounds/step/wet_grass2.ogg",
 "sounds/step/wet_grass3.ogg",
 "sounds/step/wet_grass4.ogg",
 "sounds/step/wet_grass5.ogg",
 "sounds/step/wet_grass6.ogg",
 "sounds/step/wood1.ogg",
 "sounds/step/wood2.ogg",
 "sounds/step/wood3.ogg",
 "sounds/step/wood4.ogg",
 "sounds/step/wood5.ogg",
 "sounds/step/wood6.ogg"
];

const SoundVolumes = {
 "damage/fallbig.ogg": 1,
 "damage/fallsmall.ogg": 1,
 "damage/hit1.ogg": 1,
 "damage/hit2.ogg": 1,
 "damage/hit3.ogg": 1,
 "dig/cloth1.ogg": 1,
 "dig/cloth2.ogg": 1,
 "dig/cloth3.ogg": 1,
 "dig/cloth4.ogg": 1,
 "dig/coral1.ogg": 1,
 "dig/coral2.ogg": 1,
 "dig/coral3.ogg": 1,
 "dig/coral4.ogg": 1,
 "dig/glass1.ogg": 1,
 "dig/glass2.ogg": 1,
 "dig/glass3.ogg": 1,
 "dig/grass1.ogg": 1,
 "dig/grass2.ogg": 1,
 "dig/grass3.ogg": 1,
 "dig/grass4.ogg": 1,
 "dig/gravel1.ogg": 1,
 "dig/gravel2.ogg": 1,
 "dig/gravel3.ogg": 1,
 "dig/gravel4.ogg": 1,
 "dig/sand1.ogg": 1,
 "dig/sand2.ogg": 1,
 "dig/sand3.ogg": 1,
 "dig/sand4.ogg": 1,
 "dig/snow1.ogg": 1,
 "dig/snow2.ogg": 1,
 "dig/snow3.ogg": 1,
 "dig/snow4.ogg": 1,
 "dig/stone1.ogg": 1,
 "dig/stone2.ogg": 1,
 "dig/stone3.ogg": 1,
 "dig/stone4.ogg": 1,
 "dig/wet_grass1.ogg": 1,
 "dig/wet_grass2.ogg": 1,
 "dig/wet_grass3.ogg": 1,
 "dig/wet_grass4.ogg": 1,
 "dig/wood1.ogg": 1,
 "dig/wood2.ogg": 1,
 "dig/wood3.ogg": 1,
 "dig/wood4.ogg": 1,
 "liquid/enter1.ogg": 1,
 "liquid/enter2.ogg": 1,
 "liquid/enter3.ogg": 1,
 "liquid/exit1.ogg": 1,
 "liquid/exit2.ogg": 1,
 "liquid/exit3.ogg": 1,
 "liquid/heavy_splash.ogg": 1,
 "liquid/lava.ogg": 1,
 "liquid/lavapop.ogg": 1,
 "liquid/splash.ogg": 1,
 "liquid/splash2.ogg": 1,
 "liquid/swim1.ogg": 1,
 "liquid/swim10.ogg": 1,
 "liquid/swim11.ogg": 1,
 "liquid/swim12.ogg": 1,
 "liquid/swim13.ogg": 1,
 "liquid/swim14.ogg": 1,
 "liquid/swim15.ogg": 1,
 "liquid/swim16.ogg": 1,
 "liquid/swim17.ogg": 1,
 "liquid/swim18.ogg": 1,
 "liquid/swim2.ogg": 1,
 "liquid/swim3.ogg": 1,
 "liquid/swim4.ogg": 1,
 "liquid/swim5.ogg": 1,
 "liquid/swim6.ogg": 1,
 "liquid/swim7.ogg": 1,
 "liquid/swim8.ogg": 1,
 "liquid/swim9.ogg": 1,
 "liquid/underwater_ambience.ogg": 1,
 "liquid/water.ogg": 1,
 "mob/axolotl/attack1.ogg": 1,
 "mob/axolotl/attack2.ogg": 1,
 "mob/axolotl/attack3.ogg": 1,
 "mob/axolotl/attack4.ogg": 1,
 "mob/axolotl/death1.ogg": 1,
 "mob/axolotl/death2.ogg": 1,
 "mob/axolotl/hurt1.ogg": 1,
 "mob/axolotl/hurt2.ogg": 1,
 "mob/axolotl/hurt3.ogg": 1,
 "mob/axolotl/hurt4.ogg": 1,
 "mob/axolotl/idle1.ogg": 1,
 "mob/axolotl/idle2.ogg": 1,
 "mob/axolotl/idle3.ogg": 1,
 "mob/axolotl/idle4.ogg": 1,
 "mob/axolotl/idle5.ogg": 1,
 "mob/axolotl/idle_air1.ogg": 1,
 "mob/axolotl/idle_air2.ogg": 1,
 "mob/axolotl/idle_air3.ogg": 1,
 "mob/axolotl/idle_air4.ogg": 1,
 "mob/axolotl/idle_air5.ogg": 1,
 "mob/bat/death.ogg": 1,
 "mob/bat/hurt1.ogg": 1,
 "mob/bat/hurt2.ogg": 1,
 "mob/bat/hurt3.ogg": 1,
 "mob/bat/hurt4.ogg": 1,
 "mob/bat/idle1.ogg": 1,
 "mob/bat/idle2.ogg": 1,
 "mob/bat/idle3.ogg": 1,
 "mob/bat/idle4.ogg": 1,
 "mob/bat/loop.ogg": 1,
 "mob/bat/takeoff.ogg": 1,
 "mob/bee/aggressive1.ogg": 1,
 "mob/bee/aggressive2.ogg": 1,
 "mob/bee/aggressive3.ogg": 1,
 "mob/bee/death1.ogg": 1,
 "mob/bee/death2.ogg": 1,
 "mob/bee/hurt1.ogg": 1,
 "mob/bee/hurt2.ogg": 1,
 "mob/bee/hurt3.ogg": 1,
 "mob/bee/loop1.ogg": 1,
 "mob/bee/loop2.ogg": 1,
 "mob/bee/loop3.ogg": 1,
 "mob/bee/loop4.ogg": 1,
 "mob/bee/loop5.ogg": 1,
 "mob/bee/pollinate1.ogg": 1,
 "mob/bee/pollinate2.ogg": 1,
 "mob/bee/pollinate3.ogg": 1,
 "mob/bee/pollinate4.ogg": 1,
 "mob/bee/sting.ogg": 1,
 "mob/blaze/breathe1.ogg": 1,
 "mob/blaze/breathe2.ogg": 1,
 "mob/blaze/breathe3.ogg": 1,
 "mob/blaze/breathe4.ogg": 1,
 "mob/blaze/death.ogg": 1,
 "mob/blaze/hit1.ogg": 1,
 "mob/blaze/hit2.ogg": 1,
 "mob/blaze/hit3.ogg": 1,
 "mob/blaze/hit4.ogg": 1,
 "mob/cat/beg1.ogg": 1,
 "mob/cat/beg2.ogg": 1,
 "mob/cat/beg3.ogg": 1,
 "mob/cat/eat1.ogg": 1,
 "mob/cat/eat2.ogg": 1,
 "mob/cat/hiss1.ogg": 1,
 "mob/cat/hiss2.ogg": 1,
 "mob/cat/hiss3.ogg": 1,
 "mob/cat/hitt1.ogg": 1,
 "mob/cat/hitt2.ogg": 1,
 "mob/cat/hitt3.ogg": 1,
 "mob/cat/meow1.ogg": 1,
 "mob/cat/meow2.ogg": 1,
 "mob/cat/meow3.ogg": 1,
 "mob/cat/meow4.ogg": 1,
 "mob/cat/ocelot/death1.ogg": 1,
 "mob/cat/ocelot/death2.ogg": 1,
 "mob/cat/ocelot/death3.ogg": 1,
 "mob/cat/ocelot/idle1.ogg": 1,
 "mob/cat/ocelot/idle2.ogg": 1,
 "mob/cat/ocelot/idle3.ogg": 1,
 "mob/cat/ocelot/idle4.ogg": 1,
 "mob/cat/purr1.ogg": 1,
 "mob/cat/purr2.ogg": 1,
 "mob/cat/purr3.ogg": 1,
 "mob/cat/purreow1.ogg": 1,
 "mob/cat/purreow2.ogg": 1,
 "mob/cat/stray/idle1.ogg": 1,
 "mob/cat/stray/idle2.ogg": 1,
 "mob/cat/stray/idle3.ogg": 1,
 "mob/cat/stray/idle4.ogg": 1,
 "mob/chicken/hurt1.ogg": 1,
 "mob/chicken/hurt2.ogg": 1,
 "mob/chicken/plop.ogg": 1,
 "mob/chicken/say1.ogg": 1,
 "mob/chicken/say2.ogg": 1,
 "mob/chicken/say3.ogg": 1,
 "mob/chicken/step1.ogg": 1,
 "mob/chicken/step2.ogg": 1,
 "mob/cow/hurt1.ogg": 1,
 "mob/cow/hurt2.ogg": 1,
 "mob/cow/hurt3.ogg": 1,
 "mob/cow/say1.ogg": 1,
 "mob/cow/say2.ogg": 1,
 "mob/cow/say3.ogg": 1,
 "mob/cow/say4.ogg": 1,
 "mob/cow/step1.ogg": 1,
 "mob/cow/step2.ogg": 1,
 "mob/cow/step3.ogg": 1,
 "mob/cow/step4.ogg": 1,
 "mob/creeper/death.ogg": 1,
 "mob/creeper/say1.ogg": 1,
 "mob/creeper/say2.ogg": 1,
 "mob/creeper/say3.ogg": 1,
 "mob/creeper/say4.ogg": 1,
 "mob/dolphin/attack1.ogg": 1,
 "mob/dolphin/attack2.ogg": 1,
 "mob/dolphin/attack3.ogg": 1,
 "mob/dolphin/blowhole1.ogg": 1,
 "mob/dolphin/blowhole2.ogg": 1,
 "mob/dolphin/death1.ogg": 1,
 "mob/dolphin/death2.ogg": 1,
 "mob/dolphin/eat1.ogg": 1,
 "mob/dolphin/eat2.ogg": 1,
 "mob/dolphin/eat3.ogg": 1,
 "mob/dolphin/hurt1.ogg": 1,
 "mob/dolphin/hurt2.ogg": 1,
 "mob/dolphin/hurt3.ogg": 1,
 "mob/dolphin/idle1.ogg": 1,
 "mob/dolphin/idle2.ogg": 1,
 "mob/dolphin/idle3.ogg": 1,
 "mob/dolphin/idle4.ogg": 1,
 "mob/dolphin/idle5.ogg": 1,
 "mob/dolphin/idle6.ogg": 1,
 "mob/dolphin/idle_water1.ogg": 1,
 "mob/dolphin/idle_water10.ogg": 1,
 "mob/dolphin/idle_water2.ogg": 1,
 "mob/dolphin/idle_water3.ogg": 1,
 "mob/dolphin/idle_water4.ogg": 1,
 "mob/dolphin/idle_water5.ogg": 1,
 "mob/dolphin/idle_water6.ogg": 1,
 "mob/dolphin/idle_water7.ogg": 1,
 "mob/dolphin/idle_water8.ogg": 1,
 "mob/dolphin/idle_water9.ogg": 1,
 "mob/dolphin/jump1.ogg": 1,
 "mob/dolphin/jump2.ogg": 1,
 "mob/dolphin/jump3.ogg": 1,
 "mob/dolphin/play1.ogg": 1,
 "mob/dolphin/play2.ogg": 1,
 "mob/dolphin/splash1.ogg": 1,
 "mob/dolphin/splash2.ogg": 1,
 "mob/dolphin/splash3.ogg": 1,
 "mob/dolphin/swim1.ogg": 1,
 "mob/dolphin/swim2.ogg": 1,
 "mob/dolphin/swim3.ogg": 1,
 "mob/dolphin/swim4.ogg": 1,
 "mob/drowned/convert1.ogg": 1,
 "mob/drowned/convert2.ogg": 1,
 "mob/drowned/convert3.ogg": 1,
 "mob/drowned/death1.ogg": 1,
 "mob/drowned/death2.ogg": 1,
 "mob/drowned/hurt1.ogg": 1,
 "mob/drowned/hurt2.ogg": 1,
 "mob/drowned/hurt3.ogg": 1,
 "mob/drowned/idle1.ogg": 1,
 "mob/drowned/idle2.ogg": 1,
 "mob/drowned/idle3.ogg": 1,
 "mob/drowned/idle4.ogg": 1,
 "mob/drowned/idle5.ogg": 1,
 "mob/drowned/step1.ogg": 1,
 "mob/drowned/step2.ogg": 1,
 "mob/drowned/step3.ogg": 1,
 "mob/drowned/step4.ogg": 1,
 "mob/drowned/step5.ogg": 1,
 "mob/drowned/water/death1.ogg": 1,
 "mob/drowned/water/death2.ogg": 1,
 "mob/drowned/water/hurt1.ogg": 1,
 "mob/drowned/water/hurt2.ogg": 1,
 "mob/drowned/water/hurt3.ogg": 1,
 "mob/drowned/water/idle1.ogg": 1,
 "mob/drowned/water/idle2.ogg": 1,
 "mob/drowned/water/idle3.ogg": 1,
 "mob/drowned/water/idle4.ogg": 1,
 "mob/enderdragon/end.ogg": 1,
 "mob/enderdragon/growl1.ogg": 1,
 "mob/enderdragon/growl2.ogg": 1,
 "mob/enderdragon/growl3.ogg": 1,
 "mob/enderdragon/growl4.ogg": 1,
 "mob/enderdragon/hit1.ogg": 1,
 "mob/enderdragon/hit2.ogg": 1,
 "mob/enderdragon/hit3.ogg": 1,
 "mob/enderdragon/hit4.ogg": 1,
 "mob/enderdragon/wings1.ogg": 1,
 "mob/enderdragon/wings2.ogg": 1,
 "mob/enderdragon/wings3.ogg": 1,
 "mob/enderdragon/wings4.ogg": 1,
 "mob/enderdragon/wings5.ogg": 1,
 "mob/enderdragon/wings6.ogg": 1,
 "mob/endermen/death.ogg": 1,
 "mob/endermen/hit1.ogg": 1,
 "mob/endermen/hit2.ogg": 1,
 "mob/endermen/hit3.ogg": 1,
 "mob/endermen/hit4.ogg": 1,
 "mob/endermen/idle1.ogg": 1,
 "mob/endermen/idle2.ogg": 1,
 "mob/endermen/idle3.ogg": 1,
 "mob/endermen/idle4.ogg": 1,
 "mob/endermen/idle5.ogg": 1,
 "mob/endermen/portal.ogg": 1,
 "mob/endermen/portal2.ogg": 1,
 "mob/endermen/scream1.ogg": 1,
 "mob/endermen/scream2.ogg": 1,
 "mob/endermen/scream3.ogg": 1,
 "mob/endermen/scream4.ogg": 1,
 "mob/endermen/stare.ogg": 1,
 "mob/evocation_illager/cast1.ogg": 1,
 "mob/evocation_illager/cast2.ogg": 1,
 "mob/evocation_illager/celebrate.ogg": 1,
 "mob/evocation_illager/death1.ogg": 1,
 "mob/evocation_illager/death2.ogg": 1,
 "mob/evocation_illager/fangs.ogg": 1,
 "mob/evocation_illager/hurt1.ogg": 1,
 "mob/evocation_illager/hurt2.ogg": 1,
 "mob/evocation_illager/idle1.ogg": 1,
 "mob/evocation_illager/idle2.ogg": 1,
 "mob/evocation_illager/idle3.ogg": 1,
 "mob/evocation_illager/idle4.ogg": 1,
 "mob/evocation_illager/prepare_attack1.ogg": 1,
 "mob/evocation_illager/prepare_attack2.ogg": 1,
 "mob/evocation_illager/prepare_summon.ogg": 1,
 "mob/evocation_illager/prepare_wololo.ogg": 1,
 "mob/fox/aggro1.ogg": 1,
 "mob/fox/aggro2.ogg": 1,
 "mob/fox/aggro3.ogg": 1,
 "mob/fox/aggro4.ogg": 1,
 "mob/fox/aggro5.ogg": 1,
 "mob/fox/aggro6.ogg": 1,
 "mob/fox/aggro7.ogg": 1,
 "mob/fox/bite1.ogg": 1,
 "mob/fox/bite2.ogg": 1,
 "mob/fox/bite3.ogg": 1,
 "mob/fox/death1.ogg": 1,
 "mob/fox/death2.ogg": 1,
 "mob/fox/eat1.ogg": 1,
 "mob/fox/eat2.ogg": 1,
 "mob/fox/eat3.ogg": 1,
 "mob/fox/hurt1.ogg": 1,
 "mob/fox/hurt2.ogg": 1,
 "mob/fox/hurt3.ogg": 1,
 "mob/fox/hurt4.ogg": 1,
 "mob/fox/idle1.ogg": 1,
 "mob/fox/idle2.ogg": 1,
 "mob/fox/idle3.ogg": 1,
 "mob/fox/idle4.ogg": 1,
 "mob/fox/idle5.ogg": 1,
 "mob/fox/idle6.ogg": 1,
 "mob/fox/screech1.ogg": 1,
 "mob/fox/screech2.ogg": 1,
 "mob/fox/screech3.ogg": 1,
 "mob/fox/screech4.ogg": 1,
 "mob/fox/sleep1.ogg": 1,
 "mob/fox/sleep2.ogg": 1,
 "mob/fox/sleep3.ogg": 1,
 "mob/fox/sleep4.ogg": 1,
 "mob/fox/sleep5.ogg": 1,
 "mob/fox/sniff1.ogg": 1,
 "mob/fox/sniff2.ogg": 1,
 "mob/fox/sniff3.ogg": 1,
 "mob/fox/sniff4.ogg": 1,
 "mob/fox/spit1.ogg": 1,
 "mob/fox/spit2.ogg": 1,
 "mob/fox/spit3.ogg": 1,
 "mob/ghast/affectionate_scream.ogg": 1,
 "mob/ghast/charge.ogg": 1,
 "mob/ghast/death.ogg": 1,
 "mob/ghast/fireball4.ogg": 1,
 "mob/ghast/moan1.ogg": 1,
 "mob/ghast/moan2.ogg": 1,
 "mob/ghast/moan3.ogg": 1,
 "mob/ghast/moan4.ogg": 1,
 "mob/ghast/moan5.ogg": 1,
 "mob/ghast/moan6.ogg": 1,
 "mob/ghast/moan7.ogg": 1,
 "mob/ghast/scream1.ogg": 1,
 "mob/ghast/scream2.ogg": 1,
 "mob/ghast/scream3.ogg": 1,
 "mob/ghast/scream4.ogg": 1,
 "mob/ghast/scream5.ogg": 1,
 "mob/goat/death1.ogg": 1,
 "mob/goat/death2.ogg": 1,
 "mob/goat/death3.ogg": 1,
 "mob/goat/death4.ogg": 1,
 "mob/goat/death5.ogg": 1,
 "mob/goat/eat1.ogg": 1,
 "mob/goat/eat2.ogg": 1,
 "mob/goat/eat3.ogg": 1,
 "mob/goat/hurt1.ogg": 1,
 "mob/goat/hurt2.ogg": 1,
 "mob/goat/hurt3.ogg": 1,
 "mob/goat/hurt4.ogg": 1,
 "mob/goat/idle1.ogg": 1,
 "mob/goat/idle2.ogg": 1,
 "mob/goat/idle3.ogg": 1,
 "mob/goat/idle4.ogg": 1,
 "mob/goat/idle5.ogg": 1,
 "mob/goat/idle6.ogg": 1,
 "mob/goat/idle7.ogg": 1,
 "mob/goat/idle8.ogg": 1,
 "mob/goat/impact1.ogg": 1,
 "mob/goat/impact2.ogg": 1,
 "mob/goat/impact3.ogg": 1,
 "mob/goat/jump1.ogg": 1,
 "mob/goat/jump2.ogg": 1,
 "mob/goat/pre_ram1.ogg": 1,
 "mob/goat/pre_ram2.ogg": 1,
 "mob/goat/pre_ram3.ogg": 1,
 "mob/goat/pre_ram4.ogg": 1,
 "mob/goat/scream1.ogg": 1,
 "mob/goat/scream2.ogg": 1,
 "mob/goat/scream3.ogg": 1,
 "mob/goat/scream4.ogg": 1,
 "mob/goat/scream5.ogg": 1,
 "mob/goat/scream6.ogg": 1,
 "mob/goat/scream7.ogg": 1,
 "mob/goat/scream8.ogg": 1,
 "mob/goat/scream9.ogg": 1,
 "mob/goat/screaming_death1.ogg": 1,
 "mob/goat/screaming_death2.ogg": 1,
 "mob/goat/screaming_death3.ogg": 1,
 "mob/goat/screaming_hurt1.ogg": 1,
 "mob/goat/screaming_hurt2.ogg": 1,
 "mob/goat/screaming_hurt3.ogg": 1,
 "mob/goat/screaming_milk1.ogg": 1,
 "mob/goat/screaming_milk2.ogg": 1,
 "mob/goat/screaming_milk3.ogg": 1,
 "mob/goat/screaming_milk4.ogg": 1,
 "mob/goat/screaming_milk5.ogg": 1,
 "mob/goat/screaming_pre_ram1.ogg": 1,
 "mob/goat/screaming_pre_ram2.ogg": 1,
 "mob/goat/screaming_pre_ram3.ogg": 1,
 "mob/goat/screaming_pre_ram4.ogg": 1,
 "mob/goat/screaming_pre_ram5.ogg": 1,
 "mob/goat/step1.ogg": 1,
 "mob/goat/step2.ogg": 1,
 "mob/goat/step3.ogg": 1,
 "mob/goat/step4.ogg": 1,
 "mob/goat/step5.ogg": 1,
 "mob/goat/step6.ogg": 1,
 "mob/guardian/attack_loop.ogg": 1,
 "mob/guardian/curse.ogg": 1,
 "mob/guardian/elder_death.ogg": 1,
 "mob/guardian/elder_hit1.ogg": 1,
 "mob/guardian/elder_hit2.ogg": 1,
 "mob/guardian/elder_hit3.ogg": 1,
 "mob/guardian/elder_hit4.ogg": 1,
 "mob/guardian/elder_idle1.ogg": 1,
 "mob/guardian/elder_idle2.ogg": 1,
 "mob/guardian/elder_idle3.ogg": 1,
 "mob/guardian/elder_idle4.ogg": 1,
 "mob/guardian/flop1.ogg": 1,
 "mob/guardian/flop2.ogg": 1,
 "mob/guardian/flop3.ogg": 1,
 "mob/guardian/flop4.ogg": 1,
 "mob/guardian/guardian_death.ogg": 1,
 "mob/guardian/guardian_hit1.ogg": 1,
 "mob/guardian/guardian_hit2.ogg": 1,
 "mob/guardian/guardian_hit3.ogg": 1,
 "mob/guardian/guardian_hit4.ogg": 1,
 "mob/guardian/land_death.ogg": 1,
 "mob/guardian/land_hit1.ogg": 1,
 "mob/guardian/land_hit2.ogg": 1,
 "mob/guardian/land_hit3.ogg": 1,
 "mob/guardian/land_hit4.ogg": 1,
 "mob/guardian/land_idle1.ogg": 1,
 "mob/guardian/land_idle2.ogg": 1,
 "mob/guardian/land_idle3.ogg": 1,
 "mob/guardian/land_idle4.ogg": 1,
 "mob/hoglin/angry1.ogg": 1,
 "mob/hoglin/angry2.ogg": 1,
 "mob/hoglin/angry3.ogg": 1,
 "mob/hoglin/angry4.ogg": 1,
 "mob/hoglin/angry5.ogg": 1,
 "mob/hoglin/angry6.ogg": 1,
 "mob/hoglin/attack1.ogg": 1,
 "mob/hoglin/attack2.ogg": 1,
 "mob/hoglin/converted1.ogg": 1,
 "mob/hoglin/converted2.ogg": 1,
 "mob/hoglin/death1.ogg": 1,
 "mob/hoglin/death2.ogg": 1,
 "mob/hoglin/death3.ogg": 1,
 "mob/hoglin/hurt1.ogg": 1,
 "mob/hoglin/hurt2.ogg": 1,
 "mob/hoglin/hurt3.ogg": 1,
 "mob/hoglin/hurt4.ogg": 1,
 "mob/hoglin/idle1.ogg": 1,
 "mob/hoglin/idle10.ogg": 1,
 "mob/hoglin/idle11.ogg": 1,
 "mob/hoglin/idle2.ogg": 1,
 "mob/hoglin/idle3.ogg": 1,
 "mob/hoglin/idle4.ogg": 1,
 "mob/hoglin/idle5.ogg": 1,
 "mob/hoglin/idle6.ogg": 1,
 "mob/hoglin/idle7.ogg": 1,
 "mob/hoglin/idle8.ogg": 1,
 "mob/hoglin/idle9.ogg": 1,
 "mob/hoglin/retreat1.ogg": 1,
 "mob/hoglin/retreat2.ogg": 1,
 "mob/hoglin/retreat3.ogg": 1,
 "mob/hoglin/step1.ogg": 1,
 "mob/hoglin/step2.ogg": 1,
 "mob/hoglin/step3.ogg": 1,
 "mob/hoglin/step4.ogg": 1,
 "mob/hoglin/step5.ogg": 1,
 "mob/hoglin/step6.ogg": 1,
 "mob/horse/angry1.ogg": 1,
 "mob/horse/armor.ogg": 1,
 "mob/horse/breathe1.ogg": 1,
 "mob/horse/breathe2.ogg": 1,
 "mob/horse/breathe3.ogg": 1,
 "mob/horse/death.ogg": 1,
 "mob/horse/donkey/angry1.ogg": 1,
 "mob/horse/donkey/angry2.ogg": 1,
 "mob/horse/donkey/death.ogg": 1,
 "mob/horse/donkey/hit1.ogg": 1,
 "mob/horse/donkey/hit2.ogg": 1,
 "mob/horse/donkey/hit3.ogg": 1,
 "mob/horse/donkey/idle1.ogg": 1,
 "mob/horse/donkey/idle2.ogg": 1,
 "mob/horse/donkey/idle3.ogg": 1,
 "mob/horse/gallop1.ogg": 1,
 "mob/horse/gallop2.ogg": 1,
 "mob/horse/gallop3.ogg": 1,
 "mob/horse/gallop4.ogg": 1,
 "mob/horse/hit1.ogg": 1,
 "mob/horse/hit2.ogg": 1,
 "mob/horse/hit3.ogg": 1,
 "mob/horse/hit4.ogg": 1,
 "mob/horse/idle1.ogg": 1,
 "mob/horse/idle2.ogg": 1,
 "mob/horse/idle3.ogg": 1,
 "mob/horse/jump.ogg": 1,
 "mob/horse/land.ogg": 1,
 "mob/horse/leather.ogg": 1,
 "mob/horse/skeleton/death.ogg": 1,
 "mob/horse/skeleton/hit1.ogg": 1,
 "mob/horse/skeleton/hit2.ogg": 1,
 "mob/horse/skeleton/hit3.ogg": 1,
 "mob/horse/skeleton/hit4.ogg": 1,
 "mob/horse/skeleton/idle1.ogg": 1,
 "mob/horse/skeleton/idle2.ogg": 1,
 "mob/horse/skeleton/idle3.ogg": 1,
 "mob/horse/skeleton/water/gallop1.ogg": 1,
 "mob/horse/skeleton/water/gallop2.ogg": 1,
 "mob/horse/skeleton/water/gallop3.ogg": 1,
 "mob/horse/skeleton/water/gallop4.ogg": 1,
 "mob/horse/skeleton/water/idle1.ogg": 1,
 "mob/horse/skeleton/water/idle2.ogg": 1,
 "mob/horse/skeleton/water/idle3.ogg": 1,
 "mob/horse/skeleton/water/idle4.ogg": 1,
 "mob/horse/skeleton/water/idle5.ogg": 1,
 "mob/horse/skeleton/water/jump.ogg": 1,
 "mob/horse/skeleton/water/soft1.ogg": 1,
 "mob/horse/skeleton/water/soft2.ogg": 1,
 "mob/horse/skeleton/water/soft3.ogg": 1,
 "mob/horse/skeleton/water/soft4.ogg": 1,
 "mob/horse/skeleton/water/soft5.ogg": 1,
 "mob/horse/skeleton/water/soft6.ogg": 1,
 "mob/horse/soft1.ogg": 1,
 "mob/horse/soft2.ogg": 1,
 "mob/horse/soft3.ogg": 1,
 "mob/horse/soft4.ogg": 1,
 "mob/horse/soft5.ogg": 1,
 "mob/horse/soft6.ogg": 1,
 "mob/horse/wood1.ogg": 1,
 "mob/horse/wood2.ogg": 1,
 "mob/horse/wood3.ogg": 1,
 "mob/horse/wood4.ogg": 1,
 "mob/horse/wood5.ogg": 1,
 "mob/horse/wood6.ogg": 1,
 "mob/horse/zombie/death.ogg": 1,
 "mob/horse/zombie/hit1.ogg": 1,
 "mob/horse/zombie/hit2.ogg": 1,
 "mob/horse/zombie/hit3.ogg": 1,
 "mob/horse/zombie/hit4.ogg": 1,
 "mob/horse/zombie/idle1.ogg": 1,
 "mob/horse/zombie/idle2.ogg": 1,
 "mob/horse/zombie/idle3.ogg": 1,
 "mob/husk/convert1.ogg": 1,
 "mob/husk/convert2.ogg": 1,
 "mob/husk/death1.ogg": 1,
 "mob/husk/death2.ogg": 1,
 "mob/husk/hurt1.ogg": 1,
 "mob/husk/hurt2.ogg": 1,
 "mob/husk/idle1.ogg": 1,
 "mob/husk/idle2.ogg": 1,
 "mob/husk/idle3.ogg": 1,
 "mob/husk/step1.ogg": 1,
 "mob/husk/step2.ogg": 1,
 "mob/husk/step3.ogg": 1,
 "mob/husk/step4.ogg": 1,
 "mob/husk/step5.ogg": 1,
 "mob/illusion_illager/death1.ogg": 1,
 "mob/illusion_illager/death2.ogg": 1,
 "mob/illusion_illager/hurt1.ogg": 1,
 "mob/illusion_illager/hurt2.ogg": 1,
 "mob/illusion_illager/hurt3.ogg": 1,
 "mob/illusion_illager/idle1.ogg": 1,
 "mob/illusion_illager/idle2.ogg": 1,
 "mob/illusion_illager/idle3.ogg": 1,
 "mob/illusion_illager/idle4.ogg": 1,
 "mob/illusion_illager/mirror_move1.ogg": 1,
 "mob/illusion_illager/mirror_move2.ogg": 1,
 "mob/illusion_illager/prepare_blind.ogg": 1,
 "mob/illusion_illager/prepare_mirror.ogg": 1,
 "mob/irongolem/damage1.ogg": 1,
 "mob/irongolem/damage2.ogg": 1,
 "mob/irongolem/death.ogg": 1,
 "mob/irongolem/hit1.ogg": 1,
 "mob/irongolem/hit2.ogg": 1,
 "mob/irongolem/hit3.ogg": 1,
 "mob/irongolem/hit4.ogg": 1,
 "mob/irongolem/repair.ogg": 1,
 "mob/irongolem/throw.ogg": 1,
 "mob/irongolem/walk1.ogg": 1,
 "mob/irongolem/walk2.ogg": 1,
 "mob/irongolem/walk3.ogg": 1,
 "mob/irongolem/walk4.ogg": 1,
 "mob/llama/angry1.ogg": 1,
 "mob/llama/death1.ogg": 1,
 "mob/llama/death2.ogg": 1,
 "mob/llama/eat1.ogg": 1,
 "mob/llama/eat2.ogg": 1,
 "mob/llama/eat3.ogg": 1,
 "mob/llama/hurt1.ogg": 1,
 "mob/llama/hurt2.ogg": 1,
 "mob/llama/hurt3.ogg": 1,
 "mob/llama/idle1.ogg": 1,
 "mob/llama/idle2.ogg": 1,
 "mob/llama/idle3.ogg": 1,
 "mob/llama/idle4.ogg": 1,
 "mob/llama/idle5.ogg": 1,
 "mob/llama/spit1.ogg": 1,
 "mob/llama/spit2.ogg": 1,
 "mob/llama/step1.ogg": 1,
 "mob/llama/step2.ogg": 1,
 "mob/llama/step3.ogg": 1,
 "mob/llama/step4.ogg": 1,
 "mob/llama/step5.ogg": 1,
 "mob/llama/swag.ogg": 1,
 "mob/magmacube/big1.ogg": 1,
 "mob/magmacube/big2.ogg": 1,
 "mob/magmacube/big3.ogg": 1,
 "mob/magmacube/big4.ogg": 1,
 "mob/magmacube/jump1.ogg": 1,
 "mob/magmacube/jump2.ogg": 1,
 "mob/magmacube/jump3.ogg": 1,
 "mob/magmacube/jump4.ogg": 1,
 "mob/magmacube/small1.ogg": 1,
 "mob/magmacube/small2.ogg": 1,
 "mob/magmacube/small3.ogg": 1,
 "mob/magmacube/small4.ogg": 1,
 "mob/magmacube/small5.ogg": 1,
 "mob/mooshroom/convert1.ogg": 1,
 "mob/mooshroom/convert2.ogg": 1,
 "mob/mooshroom/eat1.ogg": 1,
 "mob/mooshroom/eat2.ogg": 1,
 "mob/mooshroom/eat3.ogg": 1,
 "mob/mooshroom/eat4.ogg": 1,
 "mob/mooshroom/milk1.ogg": 1,
 "mob/mooshroom/milk2.ogg": 1,
 "mob/mooshroom/milk3.ogg": 1,
 "mob/panda/aggressive/aggressive1.ogg": 1,
 "mob/panda/aggressive/aggressive2.ogg": 1,
 "mob/panda/aggressive/aggressive3.ogg": 1,
 "mob/panda/aggressive/aggressive4.ogg": 1,
 "mob/panda/bite1.ogg": 1,
 "mob/panda/bite2.ogg": 1,
 "mob/panda/bite3.ogg": 1,
 "mob/panda/cant_breed1.ogg": 1,
 "mob/panda/cant_breed2.ogg": 1,
 "mob/panda/cant_breed3.ogg": 1,
 "mob/panda/cant_breed4.ogg": 1,
 "mob/panda/cant_breed5.ogg": 1,
 "mob/panda/death1.ogg": 1,
 "mob/panda/death2.ogg": 1,
 "mob/panda/death3.ogg": 1,
 "mob/panda/death4.ogg": 1,
 "mob/panda/eat1.ogg": 1,
 "mob/panda/eat10.ogg": 1,
 "mob/panda/eat11.ogg": 1,
 "mob/panda/eat12.ogg": 1,
 "mob/panda/eat2.ogg": 1,
 "mob/panda/eat3.ogg": 1,
 "mob/panda/eat4.ogg": 1,
 "mob/panda/eat5.ogg": 1,
 "mob/panda/eat6.ogg": 1,
 "mob/panda/eat7.ogg": 1,
 "mob/panda/eat8.ogg": 1,
 "mob/panda/eat9.ogg": 1,
 "mob/panda/hurt1.ogg": 1,
 "mob/panda/hurt2.ogg": 1,
 "mob/panda/hurt3.ogg": 1,
 "mob/panda/hurt4.ogg": 1,
 "mob/panda/hurt5.ogg": 1,
 "mob/panda/hurt6.ogg": 1,
 "mob/panda/idle1.ogg": 1,
 "mob/panda/idle2.ogg": 1,
 "mob/panda/idle3.ogg": 1,
 "mob/panda/idle4.ogg": 1,
 "mob/panda/nosebreath1.ogg": 1,
 "mob/panda/nosebreath2.ogg": 1,
 "mob/panda/nosebreath3.ogg": 1,
 "mob/panda/pant1.ogg": 1,
 "mob/panda/pant2.ogg": 1,
 "mob/panda/pre_sneeze.ogg": 1,
 "mob/panda/sneeze1.ogg": 1,
 "mob/panda/sneeze2.ogg": 1,
 "mob/panda/sneeze3.ogg": 1,
 "mob/panda/step1.ogg": 1,
 "mob/panda/step2.ogg": 1,
 "mob/panda/step3.ogg": 1,
 "mob/panda/step4.ogg": 1,
 "mob/panda/step5.ogg": 1,
 "mob/panda/worried/worried1.ogg": 1,
 "mob/panda/worried/worried2.ogg": 1,
 "mob/panda/worried/worried3.ogg": 1,
 "mob/panda/worried/worried4.ogg": 1,
 "mob/panda/worried/worried5.ogg": 1,
 "mob/panda/worried/worried6.ogg": 1,
 "mob/parrot/death1.ogg": 1,
 "mob/parrot/death2.ogg": 1,
 "mob/parrot/death3.ogg": 1,
 "mob/parrot/death4.ogg": 1,
 "mob/parrot/eat1.ogg": 1,
 "mob/parrot/eat2.ogg": 1,
 "mob/parrot/eat3.ogg": 1,
 "mob/parrot/fly1.ogg": 1,
 "mob/parrot/fly2.ogg": 1,
 "mob/parrot/fly3.ogg": 1,
 "mob/parrot/fly4.ogg": 1,
 "mob/parrot/fly5.ogg": 1,
 "mob/parrot/fly6.ogg": 1,
 "mob/parrot/fly7.ogg": 1,
 "mob/parrot/fly8.ogg": 1,
 "mob/parrot/hurt1.ogg": 1,
 "mob/parrot/hurt2.ogg": 1,
 "mob/parrot/idle1.ogg": 1,
 "mob/parrot/idle2.ogg": 1,
 "mob/parrot/idle3.ogg": 1,
 "mob/parrot/idle4.ogg": 1,
 "mob/parrot/idle5.ogg": 1,
 "mob/parrot/idle6.ogg": 1,
 "mob/parrot/step1.ogg": 1,
 "mob/parrot/step2.ogg": 1,
 "mob/parrot/step3.ogg": 1,
 "mob/parrot/step4.ogg": 1,
 "mob/parrot/step5.ogg": 1,
 "mob/phantom/bite1.ogg": 1,
 "mob/phantom/bite2.ogg": 1,
 "mob/phantom/death1.ogg": 1,
 "mob/phantom/death2.ogg": 1,
 "mob/phantom/death3.ogg": 1,
 "mob/phantom/flap1.ogg": 1,
 "mob/phantom/flap2.ogg": 1,
 "mob/phantom/flap3.ogg": 1,
 "mob/phantom/flap4.ogg": 1,
 "mob/phantom/flap5.ogg": 1,
 "mob/phantom/flap6.ogg": 1,
 "mob/phantom/hurt1.ogg": 1,
 "mob/phantom/hurt2.ogg": 1,
 "mob/phantom/hurt3.ogg": 1,
 "mob/phantom/idle1.ogg": 1,
 "mob/phantom/idle2.ogg": 1,
 "mob/phantom/idle3.ogg": 1,
 "mob/phantom/idle4.ogg": 1,
 "mob/phantom/idle5.ogg": 1,
 "mob/phantom/swoop1.ogg": 1,
 "mob/phantom/swoop2.ogg": 1,
 "mob/phantom/swoop3.ogg": 1,
 "mob/phantom/swoop4.ogg": 1,
 "mob/pig/death.ogg": 1,
 "mob/pig/say1.ogg": 1,
 "mob/pig/say2.ogg": 1,
 "mob/pig/say3.ogg": 1,
 "mob/pig/step1.ogg": 1,
 "mob/pig/step2.ogg": 1,
 "mob/pig/step3.ogg": 1,
 "mob/pig/step4.ogg": 1,
 "mob/pig/step5.ogg": 1,
 "mob/piglin/admire1.ogg": 1,
 "mob/piglin/admire2.ogg": 1,
 "mob/piglin/angry1.ogg": 1,
 "mob/piglin/angry2.ogg": 1,
 "mob/piglin/angry3.ogg": 1,
 "mob/piglin/angry4.ogg": 1,
 "mob/piglin/celebrate1.ogg": 1,
 "mob/piglin/celebrate2.ogg": 1,
 "mob/piglin/celebrate3.ogg": 1,
 "mob/piglin/celebrate4.ogg": 1,
 "mob/piglin/converted1.ogg": 1,
 "mob/piglin/converted2.ogg": 1,
 "mob/piglin/death1.ogg": 1,
 "mob/piglin/death2.ogg": 1,
 "mob/piglin/death3.ogg": 1,
 "mob/piglin/death4.ogg": 1,
 "mob/piglin/hurt1.ogg": 1,
 "mob/piglin/hurt2.ogg": 1,
 "mob/piglin/hurt3.ogg": 1,
 "mob/piglin/idle1.ogg": 1,
 "mob/piglin/idle2.ogg": 1,
 "mob/piglin/idle3.ogg": 1,
 "mob/piglin/idle4.ogg": 1,
 "mob/piglin/idle5.ogg": 1,
 "mob/piglin/jealous1.ogg": 1,
 "mob/piglin/jealous2.ogg": 1,
 "mob/piglin/jealous3.ogg": 1,
 "mob/piglin/jealous4.ogg": 1,
 "mob/piglin/jealous5.ogg": 1,
 "mob/piglin/retreat1.ogg": 1,
 "mob/piglin/retreat2.ogg": 1,
 "mob/piglin/retreat3.ogg": 1,
 "mob/piglin/retreat4.ogg": 1,
 "mob/piglin/step1.ogg": 1,
 "mob/piglin/step2.ogg": 1,
 "mob/piglin/step3.ogg": 1,
 "mob/piglin/step4.ogg": 1,
 "mob/piglin/step5.ogg": 1,
 "mob/piglin_brute/angry1.ogg": 1,
 "mob/piglin_brute/angry2.ogg": 1,
 "mob/piglin_brute/angry3.ogg": 1,
 "mob/piglin_brute/angry4.ogg": 1,
 "mob/piglin_brute/angry5.ogg": 1,
 "mob/piglin_brute/death1.ogg": 1,
 "mob/piglin_brute/death2.ogg": 1,
 "mob/piglin_brute/death3.ogg": 1,
 "mob/piglin_brute/hurt1.ogg": 1,
 "mob/piglin_brute/hurt2.ogg": 1,
 "mob/piglin_brute/hurt3.ogg": 1,
 "mob/piglin_brute/hurt4.ogg": 1,
 "mob/piglin_brute/idle1.ogg": 1,
 "mob/piglin_brute/idle2.ogg": 1,
 "mob/piglin_brute/idle3.ogg": 1,
 "mob/piglin_brute/idle4.ogg": 1,
 "mob/piglin_brute/idle5.ogg": 1,
 "mob/piglin_brute/idle6.ogg": 1,
 "mob/piglin_brute/idle7.ogg": 1,
 "mob/piglin_brute/idle8.ogg": 1,
 "mob/piglin_brute/idle9.ogg": 1,
 "mob/piglin_brute/step1.ogg": 1,
 "mob/piglin_brute/step2.ogg": 1,
 "mob/piglin_brute/step3.ogg": 1,
 "mob/piglin_brute/step4.ogg": 1,
 "mob/piglin_brute/step5.ogg": 1,
 "mob/pillager/celebrate1.ogg": 1,
 "mob/pillager/celebrate2.ogg": 1,
 "mob/pillager/celebrate3.ogg": 1,
 "mob/pillager/celebrate4.ogg": 1,
 "mob/pillager/death1.ogg": 1,
 "mob/pillager/death2.ogg": 1,
 "mob/pillager/horn_celebrate.ogg": 1,
 "mob/pillager/hurt1.ogg": 1,
 "mob/pillager/hurt2.ogg": 1,
 "mob/pillager/hurt3.ogg": 1,
 "mob/pillager/idle1.ogg": 1,
 "mob/pillager/idle2.ogg": 1,
 "mob/pillager/idle3.ogg": 1,
 "mob/pillager/idle4.ogg": 1,
 "mob/polarbear/death1.ogg": 1,
 "mob/polarbear/death2.ogg": 1,
 "mob/polarbear/death3.ogg": 1,
 "mob/polarbear/hurt1.ogg": 1,
 "mob/polarbear/hurt2.ogg": 1,
 "mob/polarbear/hurt3.ogg": 1,
 "mob/polarbear/hurt4.ogg": 1,
 "mob/polarbear/idle1.ogg": 1,
 "mob/polarbear/idle2.ogg": 1,
 "mob/polarbear/idle3.ogg": 1,
 "mob/polarbear/idle4.ogg": 1,
 "mob/polarbear/step1.ogg": 1,
 "mob/polarbear/step2.ogg": 1,
 "mob/polarbear/step3.ogg": 1,
 "mob/polarbear/step4.ogg": 1,
 "mob/polarbear/warning1.ogg": 1,
 "mob/polarbear/warning2.ogg": 1,
 "mob/polarbear/warning3.ogg": 1,
 "mob/polarbear_baby/idle1.ogg": 1,
 "mob/polarbear_baby/idle2.ogg": 1,
 "mob/polarbear_baby/idle3.ogg": 1,
 "mob/polarbear_baby/idle4.ogg": 1,
 "mob/rabbit/bunnymurder.ogg": 1,
 "mob/rabbit/hop1.ogg": 1,
 "mob/rabbit/hop2.ogg": 1,
 "mob/rabbit/hop3.ogg": 1,
 "mob/rabbit/hop4.ogg": 1,
 "mob/rabbit/hurt1.ogg": 1,
 "mob/rabbit/hurt2.ogg": 1,
 "mob/rabbit/hurt3.ogg": 1,
 "mob/rabbit/hurt4.ogg": 1,
 "mob/rabbit/idle1.ogg": 1,
 "mob/rabbit/idle2.ogg": 1,
 "mob/rabbit/idle3.ogg": 1,
 "mob/rabbit/idle4.ogg": 1,
 "mob/ravager/bite1.ogg": 1,
 "mob/ravager/bite2.ogg": 1,
 "mob/ravager/bite3.ogg": 1,
 "mob/ravager/celebrate1.ogg": 1,
 "mob/ravager/celebrate2.ogg": 1,
 "mob/ravager/death1.ogg": 1,
 "mob/ravager/death2.ogg": 1,
 "mob/ravager/death3.ogg": 1,
 "mob/ravager/hurt1.ogg": 1,
 "mob/ravager/hurt2.ogg": 1,
 "mob/ravager/hurt3.ogg": 1,
 "mob/ravager/hurt4.ogg": 1,
 "mob/ravager/idle1.ogg": 1,
 "mob/ravager/idle2.ogg": 1,
 "mob/ravager/idle3.ogg": 1,
 "mob/ravager/idle4.ogg": 1,
 "mob/ravager/idle5.ogg": 1,
 "mob/ravager/idle6.ogg": 1,
 "mob/ravager/idle7.ogg": 1,
 "mob/ravager/idle8.ogg": 1,
 "mob/ravager/roar1.ogg": 1,
 "mob/ravager/roar2.ogg": 1,
 "mob/ravager/roar3.ogg": 1,
 "mob/ravager/roar4.ogg": 1,
 "mob/ravager/step1.ogg": 1,
 "mob/ravager/step2.ogg": 1,
 "mob/ravager/step3.ogg": 1,
 "mob/ravager/step4.ogg": 1,
 "mob/ravager/step5.ogg": 1,
 "mob/ravager/stun1.ogg": 1,
 "mob/ravager/stun2.ogg": 1,
 "mob/ravager/stun3.ogg": 1,
 "mob/sheep/say1.ogg": 1,
 "mob/sheep/say2.ogg": 1,
 "mob/sheep/say3.ogg": 1,
 "mob/sheep/shear.ogg": 1,
 "mob/sheep/step1.ogg": 1,
 "mob/sheep/step2.ogg": 1,
 "mob/sheep/step3.ogg": 1,
 "mob/sheep/step4.ogg": 1,
 "mob/sheep/step5.ogg": 1,
 "mob/silverfish/hit1.ogg": 1,
 "mob/silverfish/hit2.ogg": 1,
 "mob/silverfish/hit3.ogg": 1,
 "mob/silverfish/kill.ogg": 1,
 "mob/silverfish/say1.ogg": 1,
 "mob/silverfish/say2.ogg": 1,
 "mob/silverfish/say3.ogg": 1,
 "mob/silverfish/say4.ogg": 1,
 "mob/silverfish/step1.ogg": 1,
 "mob/silverfish/step2.ogg": 1,
 "mob/silverfish/step3.ogg": 1,
 "mob/silverfish/step4.ogg": 1,
 "mob/skeleton/death.ogg": 1,
 "mob/skeleton/hurt1.ogg": 1,
 "mob/skeleton/hurt2.ogg": 1,
 "mob/skeleton/hurt3.ogg": 1,
 "mob/skeleton/hurt4.ogg": 1,
 "mob/skeleton/say1.ogg": 1,
 "mob/skeleton/say2.ogg": 1,
 "mob/skeleton/say3.ogg": 1,
 "mob/skeleton/step1.ogg": 1,
 "mob/skeleton/step2.ogg": 1,
 "mob/skeleton/step3.ogg": 1,
 "mob/skeleton/step4.ogg": 1,
 "mob/slime/attack1.ogg": 1,
 "mob/slime/attack2.ogg": 1,
 "mob/slime/big1.ogg": 1,
 "mob/slime/big2.ogg": 1,
 "mob/slime/big3.ogg": 1,
 "mob/slime/big4.ogg": 1,
 "mob/slime/small1.ogg": 1,
 "mob/slime/small2.ogg": 1,
 "mob/slime/small3.ogg": 1,
 "mob/slime/small4.ogg": 1,
 "mob/slime/small5.ogg": 1,
 "mob/spider/death.ogg": 1,
 "mob/spider/say1.ogg": 1,
 "mob/spider/say2.ogg": 1,
 "mob/spider/say3.ogg": 1,
 "mob/spider/say4.ogg": 1,
 "mob/spider/step1.ogg": 1,
 "mob/spider/step2.ogg": 1,
 "mob/spider/step3.ogg": 1,
 "mob/spider/step4.ogg": 1,
 "mob/stray/convert1.ogg": 1,
 "mob/stray/convert2.ogg": 1,
 "mob/stray/convert3.ogg": 1,
 "mob/stray/death1.ogg": 1,
 "mob/stray/death2.ogg": 1,
 "mob/stray/hurt1.ogg": 1,
 "mob/stray/hurt2.ogg": 1,
 "mob/stray/hurt3.ogg": 1,
 "mob/stray/hurt4.ogg": 1,
 "mob/stray/idle1.ogg": 1,
 "mob/stray/idle2.ogg": 1,
 "mob/stray/idle3.ogg": 1,
 "mob/stray/idle4.ogg": 1,
 "mob/stray/step1.ogg": 1,
 "mob/stray/step2.ogg": 1,
 "mob/stray/step3.ogg": 1,
 "mob/stray/step4.ogg": 1,
 "mob/strider/death1.ogg": 1,
 "mob/strider/death2.ogg": 1,
 "mob/strider/death3.ogg": 1,
 "mob/strider/death4.ogg": 1,
 "mob/strider/eat1.ogg": 1,
 "mob/strider/eat2.ogg": 1,
 "mob/strider/eat3.ogg": 1,
 "mob/strider/happy1.ogg": 1,
 "mob/strider/happy2.ogg": 1,
 "mob/strider/happy3.ogg": 1,
 "mob/strider/happy4.ogg": 1,
 "mob/strider/happy5.ogg": 1,
 "mob/strider/hurt1.ogg": 1,
 "mob/strider/hurt2.ogg": 1,
 "mob/strider/hurt3.ogg": 1,
 "mob/strider/hurt4.ogg": 1,
 "mob/strider/idle1.ogg": 1,
 "mob/strider/idle2.ogg": 1,
 "mob/strider/idle3.ogg": 1,
 "mob/strider/idle4.ogg": 1,
 "mob/strider/idle5.ogg": 1,
 "mob/strider/idle6.ogg": 1,
 "mob/strider/retreat1.ogg": 1,
 "mob/strider/retreat2.ogg": 1,
 "mob/strider/retreat3.ogg": 1,
 "mob/strider/retreat4.ogg": 1,
 "mob/strider/retreat5.ogg": 1,
 "mob/strider/step1.ogg": 1,
 "mob/strider/step2.ogg": 1,
 "mob/strider/step3.ogg": 1,
 "mob/strider/step4.ogg": 1,
 "mob/strider/step5.ogg": 1,
 "mob/strider/step_lava1.ogg": 1,
 "mob/strider/step_lava2.ogg": 1,
 "mob/strider/step_lava3.ogg": 1,
 "mob/strider/step_lava4.ogg": 1,
 "mob/strider/step_lava5.ogg": 1,
 "mob/strider/step_lava6.ogg": 1,
 "mob/turtle/armor.ogg": 1,
 "mob/turtle/baby/death1.ogg": 1,
 "mob/turtle/baby/death2.ogg": 1,
 "mob/turtle/baby/egg_hatched1.ogg": 1,
 "mob/turtle/baby/egg_hatched2.ogg": 1,
 "mob/turtle/baby/egg_hatched3.ogg": 1,
 "mob/turtle/baby/hurt1.ogg": 1,
 "mob/turtle/baby/hurt2.ogg": 1,
 "mob/turtle/baby/shamble1.ogg": 1,
 "mob/turtle/baby/shamble2.ogg": 1,
 "mob/turtle/baby/shamble3.ogg": 1,
 "mob/turtle/baby/shamble4.ogg": 1,
 "mob/turtle/death1.ogg": 1,
 "mob/turtle/death2.ogg": 1,
 "mob/turtle/death3.ogg": 1,
 "mob/turtle/egg/drop_egg1.ogg": 1,
 "mob/turtle/egg/drop_egg2.ogg": 1,
 "mob/turtle/egg/egg_break1.ogg": 1,
 "mob/turtle/egg/egg_break2.ogg": 1,
 "mob/turtle/egg/egg_crack1.ogg": 1,
 "mob/turtle/egg/egg_crack2.ogg": 1,
 "mob/turtle/egg/egg_crack3.ogg": 1,
 "mob/turtle/egg/egg_crack4.ogg": 1,
 "mob/turtle/egg/egg_crack5.ogg": 1,
 "mob/turtle/egg/jump_egg1.ogg": 1,
 "mob/turtle/egg/jump_egg2.ogg": 1,
 "mob/turtle/egg/jump_egg3.ogg": 1,
 "mob/turtle/egg/jump_egg4.ogg": 1,
 "mob/turtle/hurt1.ogg": 1,
 "mob/turtle/hurt2.ogg": 1,
 "mob/turtle/hurt3.ogg": 1,
 "mob/turtle/hurt4.ogg": 1,
 "mob/turtle/hurt5.ogg": 1,
 "mob/turtle/idle1.ogg": 1,
 "mob/turtle/idle2.ogg": 1,
 "mob/turtle/idle3.ogg": 1,
 "mob/turtle/swim/swim1.ogg": 1,
 "mob/turtle/swim/swim2.ogg": 1,
 "mob/turtle/swim/swim3.ogg": 1,
 "mob/turtle/swim/swim4.ogg": 1,
 "mob/turtle/swim/swim5.ogg": 1,
 "mob/turtle/walk1.ogg": 1,
 "mob/turtle/walk2.ogg": 1,
 "mob/turtle/walk3.ogg": 1,
 "mob/turtle/walk4.ogg": 1,
 "mob/turtle/walk5.ogg": 1,
 "mob/vex/charge1.ogg": 1,
 "mob/vex/charge2.ogg": 1,
 "mob/vex/charge3.ogg": 1,
 "mob/vex/death1.ogg": 1,
 "mob/vex/death2.ogg": 1,
 "mob/vex/hurt1.ogg": 1,
 "mob/vex/hurt2.ogg": 1,
 "mob/vex/idle1.ogg": 1,
 "mob/vex/idle2.ogg": 1,
 "mob/vex/idle3.ogg": 1,
 "mob/vex/idle4.ogg": 1,
 "mob/villager/death.ogg": 1,
 "mob/villager/haggle1.ogg": 1,
 "mob/villager/haggle2.ogg": 1,
 "mob/villager/haggle3.ogg": 1,
 "mob/villager/hit1.ogg": 1,
 "mob/villager/hit2.ogg": 1,
 "mob/villager/hit3.ogg": 1,
 "mob/villager/hit4.ogg": 1,
 "mob/villager/idle1.ogg": 1,
 "mob/villager/idle2.ogg": 1,
 "mob/villager/idle3.ogg": 1,
 "mob/villager/no1.ogg": 1,
 "mob/villager/no2.ogg": 1,
 "mob/villager/no3.ogg": 1,
 "mob/villager/yes1.ogg": 1,
 "mob/villager/yes2.ogg": 1,
 "mob/villager/yes3.ogg": 1,
 "mob/vindication_illager/celebrate1.ogg": 1,
 "mob/vindication_illager/celebrate2.ogg": 1,
 "mob/vindication_illager/death1.ogg": 1,
 "mob/vindication_illager/death2.ogg": 1,
 "mob/vindication_illager/hurt1.ogg": 1,
 "mob/vindication_illager/hurt2.ogg": 1,
 "mob/vindication_illager/hurt3.ogg": 1,
 "mob/vindication_illager/idle1.ogg": 1,
 "mob/vindication_illager/idle2.ogg": 1,
 "mob/vindication_illager/idle3.ogg": 1,
 "mob/vindication_illager/idle4.ogg": 1,
 "mob/vindication_illager/idle5.ogg": 1,
 "mob/wandering_trader/appeared1.ogg": 1,
 "mob/wandering_trader/appeared2.ogg": 1,
 "mob/wandering_trader/death.ogg": 1,
 "mob/wandering_trader/disappeared1.ogg": 1,
 "mob/wandering_trader/disappeared2.ogg": 1,
 "mob/wandering_trader/drink_milk1.ogg": 1,
 "mob/wandering_trader/drink_milk2.ogg": 1,
 "mob/wandering_trader/drink_milk3.ogg": 1,
 "mob/wandering_trader/drink_milk4.ogg": 1,
 "mob/wandering_trader/drink_milk5.ogg": 1,
 "mob/wandering_trader/drink_potion.ogg": 1,
 "mob/wandering_trader/haggle1.ogg": 1,
 "mob/wandering_trader/haggle2.ogg": 1,
 "mob/wandering_trader/haggle3.ogg": 1,
 "mob/wandering_trader/hurt1.ogg": 1,
 "mob/wandering_trader/hurt2.ogg": 1,
 "mob/wandering_trader/hurt3.ogg": 1,
 "mob/wandering_trader/hurt4.ogg": 1,
 "mob/wandering_trader/idle1.ogg": 1,
 "mob/wandering_trader/idle2.ogg": 1,
 "mob/wandering_trader/idle3.ogg": 1,
 "mob/wandering_trader/idle4.ogg": 1,
 "mob/wandering_trader/idle5.ogg": 1,
 "mob/wandering_trader/no1.ogg": 1,
 "mob/wandering_trader/no2.ogg": 1,
 "mob/wandering_trader/no3.ogg": 1,
 "mob/wandering_trader/no4.ogg": 1,
 "mob/wandering_trader/no5.ogg": 1,
 "mob/wandering_trader/reappeared1.ogg": 1,
 "mob/wandering_trader/reappeared2.ogg": 1,
 "mob/wandering_trader/yes1.ogg": 1,
 "mob/wandering_trader/yes2.ogg": 1,
 "mob/wandering_trader/yes3.ogg": 1,
 "mob/wandering_trader/yes4.ogg": 1,
 "mob/wither/death.ogg": 1,
 "mob/wither/hurt1.ogg": 1,
 "mob/wither/hurt2.ogg": 1,
 "mob/wither/hurt3.ogg": 1,
 "mob/wither/hurt4.ogg": 1,
 "mob/wither/idle1.ogg": 1,
 "mob/wither/idle2.ogg": 1,
 "mob/wither/idle3.ogg": 1,
 "mob/wither/idle4.ogg": 1,
 "mob/wither/shoot.ogg": 1,
 "mob/wither/spawn.ogg": 1,
 "mob/wither_skeleton/death1.ogg": 1,
 "mob/wither_skeleton/death2.ogg": 1,
 "mob/wither_skeleton/hurt1.ogg": 1,
 "mob/wither_skeleton/hurt2.ogg": 1,
 "mob/wither_skeleton/hurt3.ogg": 1,
 "mob/wither_skeleton/hurt4.ogg": 1,
 "mob/wither_skeleton/idle1.ogg": 1,
 "mob/wither_skeleton/idle2.ogg": 1,
 "mob/wither_skeleton/idle3.ogg": 1,
 "mob/wither_skeleton/step1.ogg": 1,
 "mob/wither_skeleton/step2.ogg": 1,
 "mob/wither_skeleton/step3.ogg": 1,
 "mob/wither_skeleton/step4.ogg": 1,
 "mob/wolf/bark1.ogg": 1,
 "mob/wolf/bark2.ogg": 1,
 "mob/wolf/bark3.ogg": 1,
 "mob/wolf/death.ogg": 1,
 "mob/wolf/growl1.ogg": 1,
 "mob/wolf/growl2.ogg": 1,
 "mob/wolf/growl3.ogg": 1,
 "mob/wolf/howl1.ogg": 1,
 "mob/wolf/howl2.ogg": 1,
 "mob/wolf/hurt1.ogg": 1,
 "mob/wolf/hurt2.ogg": 1,
 "mob/wolf/hurt3.ogg": 1,
 "mob/wolf/panting.ogg": 1,
 "mob/wolf/shake.ogg": 1,
 "mob/wolf/step1.ogg": 1,
 "mob/wolf/step2.ogg": 1,
 "mob/wolf/step3.ogg": 1,
 "mob/wolf/step4.ogg": 1,
 "mob/wolf/step5.ogg": 1,
 "mob/wolf/whine.ogg": 1,
 "mob/zoglin/angry1.ogg": 1,
 "mob/zoglin/angry2.ogg": 1,
 "mob/zoglin/angry3.ogg": 1,
 "mob/zoglin/attack1.ogg": 1,
 "mob/zoglin/attack2.ogg": 1,
 "mob/zoglin/death1.ogg": 1,
 "mob/zoglin/death2.ogg": 1,
 "mob/zoglin/death3.ogg": 1,
 "mob/zoglin/hurt1.ogg": 1,
 "mob/zoglin/hurt2.ogg": 1,
 "mob/zoglin/hurt3.ogg": 1,
 "mob/zoglin/idle1.ogg": 1,
 "mob/zoglin/idle2.ogg": 1,
 "mob/zoglin/idle3.ogg": 1,
 "mob/zoglin/idle4.ogg": 1,
 "mob/zoglin/idle5.ogg": 1,
 "mob/zoglin/idle6.ogg": 1,
 "mob/zoglin/step1.ogg": 1,
 "mob/zoglin/step2.ogg": 1,
 "mob/zoglin/step3.ogg": 1,
 "mob/zoglin/step4.ogg": 1,
 "mob/zoglin/step5.ogg": 1,
 "mob/zombie/death.ogg": 1,
 "mob/zombie/hurt1.ogg": 1,
 "mob/zombie/hurt2.ogg": 1,
 "mob/zombie/infect.ogg": 1,
 "mob/zombie/metal1.ogg": 1,
 "mob/zombie/metal2.ogg": 1,
 "mob/zombie/metal3.ogg": 1,
 "mob/zombie/remedy.ogg": 1,
 "mob/zombie/say1.ogg": 1,
 "mob/zombie/say2.ogg": 1,
 "mob/zombie/say3.ogg": 1,
 "mob/zombie/step1.ogg": 1,
 "mob/zombie/step2.ogg": 1,
 "mob/zombie/step3.ogg": 1,
 "mob/zombie/step4.ogg": 1,
 "mob/zombie/step5.ogg": 1,
 "mob/zombie/unfect.ogg": 1,
 "mob/zombie/wood1.ogg": 1,
 "mob/zombie/wood2.ogg": 1,
 "mob/zombie/wood3.ogg": 1,
 "mob/zombie/wood4.ogg": 1,
 "mob/zombie/woodbreak.ogg": 1,
 "mob/zombie_villager/death.ogg": 1,
 "mob/zombie_villager/hurt1.ogg": 1,
 "mob/zombie_villager/hurt2.ogg": 1,
 "mob/zombie_villager/say1.ogg": 1,
 "mob/zombie_villager/say2.ogg": 1,
 "mob/zombie_villager/say3.ogg": 1,
 "mob/zombified_piglin/zpig1.ogg": 1,
 "mob/zombified_piglin/zpig2.ogg": 1,
 "mob/zombified_piglin/zpig3.ogg": 1,
 "mob/zombified_piglin/zpig4.ogg": 1,
 "mob/zombified_piglin/zpigangry1.ogg": 1,
 "mob/zombified_piglin/zpigangry2.ogg": 1,
 "mob/zombified_piglin/zpigangry3.ogg": 1,
 "mob/zombified_piglin/zpigangry4.ogg": 1,
 "mob/zombified_piglin/zpigdeath.ogg": 1,
 "mob/zombified_piglin/zpighurt1.ogg": 1,
 "mob/zombified_piglin/zpighurt2.ogg": 1,
 "random/anvil_break.ogg": 1,
 "random/anvil_land.ogg": 1,
 "random/anvil_use.ogg": 1,
 "random/bow.ogg": 1,
 "random/bowhit1.ogg": 1,
 "random/bowhit2.ogg": 1,
 "random/bowhit3.ogg": 1,
 "random/bowhit4.ogg": 1,
 "random/break.ogg": 1,
 "random/breath.ogg": 1,
 "random/burp.ogg": 1,
 "random/chestclosed.ogg": 1,
 "random/chestopen.ogg": 1,
 "random/classic_hurt.ogg": 1,
 "random/click.ogg": 1,
 "random/click_stereo.ogg": 1,
 "random/door_close.ogg": 1,
 "random/door_open.ogg": 1,
 "random/drink.ogg": 1,
 "random/eat1.ogg": 1,
 "random/eat2.ogg": 1,
 "random/eat3.ogg": 1,
 "random/explode1.ogg": 1,
 "random/explode2.ogg": 1,
 "random/explode3.ogg": 1,
 "random/explode4.ogg": 1,
 "random/fire.ogg": 1,
 "random/fizz.ogg": 1,
 "random/fuse.ogg": 1,
 "random/ignite.ogg": 1,
 "random/levelup.ogg": 1,
 "random/orb.ogg": 1,
 "random/pop.ogg": 1,
 "random/splash.ogg": 1,
 "random/successful_hit.ogg": 1,
 "random/wood_click.ogg": 1,
 "step/cloth1.ogg": 1,
 "step/cloth2.ogg": 1,
 "step/cloth3.ogg": 1,
 "step/cloth4.ogg": 1,
 "step/coral1.ogg": 1,
 "step/coral2.ogg": 1,
 "step/coral3.ogg": 1,
 "step/coral4.ogg": 1,
 "step/coral5.ogg": 1,
 "step/coral6.ogg": 1,
 "step/grass1.ogg": 1,
 "step/grass2.ogg": 1,
 "step/grass3.ogg": 1,
 "step/grass4.ogg": 1,
 "step/grass5.ogg": 1,
 "step/grass6.ogg": 1,
 "step/gravel1.ogg": 1,
 "step/gravel2.ogg": 1,
 "step/gravel3.ogg": 1,
 "step/gravel4.ogg": 1,
 "step/ladder1.ogg": 1,
 "step/ladder2.ogg": 1,
 "step/ladder3.ogg": 1,
 "step/ladder4.ogg": 1,
 "step/ladder5.ogg": 1,
 "step/sand1.ogg": 1,
 "step/sand2.ogg": 1,
 "step/sand3.ogg": 1,
 "step/sand4.ogg": 1,
 "step/sand5.ogg": 1,
 "step/scaffold1.ogg": 1,
 "step/scaffold2.ogg": 1,
 "step/scaffold3.ogg": 1,
 "step/scaffold4.ogg": 1,
 "step/scaffold5.ogg": 1,
 "step/scaffold6.ogg": 1,
 "step/scaffold7.ogg": 1,
 "step/snow1.ogg": 1,
 "step/snow2.ogg": 1,
 "step/snow3.ogg": 1,
 "step/snow4.ogg": 1,
 "step/stone1.ogg": 1,
 "step/stone2.ogg": 1,
 "step/stone3.ogg": 1,
 "step/stone4.ogg": 1,
 "step/stone5.ogg": 1,
 "step/stone6.ogg": 1,
 "step/wet_grass1.ogg": 1,
 "step/wet_grass2.ogg": 1,
 "step/wet_grass3.ogg": 1,
 "step/wet_grass4.ogg": 1,
 "step/wet_grass5.ogg": 1,
 "step/wet_grass6.ogg": 1,
 "step/wood1.ogg": 1,
 "step/wood2.ogg": 1,
 "step/wood3.ogg": 1,
 "step/wood4.ogg": 1,
 "step/wood5.ogg": 1,
 "step/wood6.ogg": 1
}